// This file was auto-generated by Fern from our API Definition.

import * as Pipedream from "../../../src/api/index";
import { PipedreamClient } from "../../../src/Client";
import { mockServerPool } from "../../mock-server/MockServerPool";
import { mockOAuth } from "../mockAuth";

describe("ComponentsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    app_name_slug: "app_name_slug",
                    component_type: "component_type",
                    description: "description",
                    id: "id",
                    key: "key",
                    name: "name",
                    version: "version",
                },
            ],
            page_info: { count: 1, page: 1000000, per_page: 1000000, total_count: 1000000 },
        };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.v2.components.list({
            q: "q",
            limit: 1000000,
            page: 1000000,
            componentType: "component_type",
            app: "app",
            registry: "registry",
        });
        expect(response).toEqual({
            data: [
                {
                    appNameSlug: "app_name_slug",
                    componentType: "component_type",
                    description: "description",
                    id: "id",
                    key: "key",
                    name: "name",
                    version: "version",
                },
            ],
            pageInfo: {
                count: 1,
                page: 1000000,
                perPage: 1000000,
                totalCount: 1000000,
            },
        });
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.list();
        }).rejects.toThrow(Pipedream.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.list();
        }).rejects.toThrow(Pipedream.UnauthorizedError);
    });

    test("list (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.list();
        }).rejects.toThrow(Pipedream.InternalServerError);
    });

    test("list (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.list();
        }).rejects.toThrow(Pipedream.BadGatewayError);
    });

    test("list (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.list();
        }).rejects.toThrow(Pipedream.ServiceUnavailableError);
    });

    test("facets (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { data: { key: [{ count: 1000000, value: "value" }] } };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/facets")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.v2.components.facets({
            registry: "registry",
        });
        expect(response).toEqual({
            data: {
                key: [
                    {
                        count: 1000000,
                        value: "value",
                    },
                ],
            },
        });
    });

    test("facets (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/facets")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.facets();
        }).rejects.toThrow(Pipedream.BadRequestError);
    });

    test("facets (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/facets")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.facets();
        }).rejects.toThrow(Pipedream.UnauthorizedError);
    });

    test("facets (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/facets")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.facets();
        }).rejects.toThrow(Pipedream.InternalServerError);
    });

    test("facets (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/facets")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.facets();
        }).rejects.toThrow(Pipedream.BadGatewayError);
    });

    test("facets (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/facets")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.facets();
        }).rejects.toThrow(Pipedream.ServiceUnavailableError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                app_name_slug: "app_name_slug",
                component_type: "component_type",
                description: "description",
                id: "id",
                key: "key",
                name: "name",
                version: "version",
            },
        };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.v2.components.retrieve("id", {
            registry: "registry",
        });
        expect(response).toEqual({
            data: {
                appNameSlug: "app_name_slug",
                componentType: "component_type",
                description: "description",
                id: "id",
                key: "key",
                name: "name",
                version: "version",
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.retrieve("id");
        }).rejects.toThrow(Pipedream.BadRequestError);
    });

    test("retrieve (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(401)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.retrieve("id");
        }).rejects.toThrow(Pipedream.UnauthorizedError);
    });

    test("retrieve (4)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.retrieve("id");
        }).rejects.toThrow(Pipedream.NotFoundError);
    });

    test("retrieve (5)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(500)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.retrieve("id");
        }).rejects.toThrow(Pipedream.InternalServerError);
    });

    test("retrieve (6)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(502)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.retrieve("id");
        }).rejects.toThrow(Pipedream.BadGatewayError);
    });

    test("retrieve (7)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { error: "error" };

        server
            .mockEndpoint()
            .get("/v2/connect/project_id/components/id")
            .respondWith()
            .statusCode(503)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.v2.components.retrieve("id");
        }).rejects.toThrow(Pipedream.ServiceUnavailableError);
    });
});
