// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";
import { ConfiguredProps } from "../../../../types/ConfiguredProps.js";

export const DeployTriggerOpts: core.serialization.Schema<
    serializers.DeployTriggerOpts.Raw,
    Omit<Pipedream.DeployTriggerOpts, "projectId">
> = core.serialization.object({
    id: core.serialization.string(),
    version: core.serialization.string().optionalNullable(),
    externalUserId: core.serialization.property("external_user_id", core.serialization.string()),
    configuredProps: core.serialization.property("configured_props", ConfiguredProps.optional()),
    dynamicPropsId: core.serialization.property("dynamic_props_id", core.serialization.string().optional()),
    workflowId: core.serialization.property("workflow_id", core.serialization.string().optional()),
    webhookUrl: core.serialization.property("webhook_url", core.serialization.string().optional()),
    emitOnDeploy: core.serialization.property("emit_on_deploy", core.serialization.boolean().optionalNullable()),
});

export declare namespace DeployTriggerOpts {
    export interface Raw {
        id: string;
        version?: (string | null | undefined) | null;
        external_user_id: string;
        configured_props?: ConfiguredProps.Raw | null;
        dynamic_props_id?: string | null;
        workflow_id?: string | null;
        webhook_url?: string | null;
        emit_on_deploy?: (boolean | null | undefined) | null;
    }
}
