// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateTriggerWebhooksOpts: core.serialization.Schema<
    serializers.UpdateTriggerWebhooksOpts.Raw,
    Omit<Pipedream.UpdateTriggerWebhooksOpts, "externalUserId">
> = core.serialization.object({
    webhookUrls: core.serialization.property("webhook_urls", core.serialization.list(core.serialization.string())),
});

export declare namespace UpdateTriggerWebhooksOpts {
    export interface Raw {
        webhook_urls: string[];
    }
}
