/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";

export const UpdateTriggerWorkflowsOpts: core.serialization.Schema<
    serializers.UpdateTriggerWorkflowsOpts.Raw,
    Omit<Pipedream.UpdateTriggerWorkflowsOpts, "externalUserId">
> = core.serialization.object({
    workflowIds: core.serialization.property("workflow_ids", core.serialization.list(core.serialization.string())),
});

export declare namespace UpdateTriggerWorkflowsOpts {
    export interface Raw {
        workflow_ids: string[];
    }
}
