/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type DeployedTriggersListRequestEmitterType = "source" | "timer" | "http" | "email";
export const DeployedTriggersListRequestEmitterType = {
    Source: "source",
    Timer: "timer",
    Http: "http",
    Email: "email",
} as const;
