// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         q: "q",
 *         limit: 1000000,
 *         page: 1000000,
 *         categoryName: "category_name",
 *         authType: "auth_type",
 *         hasComponents: "has_components",
 *         hasActions: "has_actions",
 *         hasTriggers: "has_triggers",
 *         hasPrivateComponents: "has_private_components"
 *     }
 */
export interface AppsListRequest {
    q?: string;
    limit?: number;
    page?: number;
    categoryName?: string;
    authType?: string;
    /**
     * Component filters, mirroring Rails `V1::AppsController#having_components`:
     * the param's presence selects the filter and its boolean value picks the
     * direction (`false`/`0`/`f`/`off`/empty → apps *without*, anything else →
     * apps *with*). `has_components` means "has actions or triggers". Only the
     * first present of `has_components` > `has_actions` > `has_triggers` applies.
     */
    hasComponents?: string;
    hasActions?: string;
    hasTriggers?: string;
    /**
     * Not supported yet in the Rust port — Rails uses
     * `PublishedComponentTypesenseSearch.app_slugs_for_owner_keys` here, and
     * we haven't ported that. Returns 501 when set.
     */
    hasPrivateComponents?: string;
}
