// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         app: "app"
 *     }
 */
export interface CreateOauthAppOpts {
    /** The app's ID or name slug. The app must have custom OAuth clients enabled. */
    app: string;
    /** The OAuth client ID registered with the upstream provider. Optional: providers that only issue credentials once they have a callback URL can be registered without one, and the client cannot connect accounts until it is set. */
    clientId?: string;
    /** The OAuth client secret. Optional, like the client ID. Write-only; never returned in responses. */
    clientSecret?: string;
    /** Display name of the OAuth client */
    name?: string;
    /** Description of the OAuth client */
    description?: string;
    /** OAuth scopes to request when users connect through this client */
    scopes?: string[];
    /** Extra OAuth scopes users may grant on top of the base scopes */
    additionalScopes?: string[];
}
