// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const UpdateAppOverrideOpts: core.serialization.Schema<
    serializers.UpdateAppOverrideOpts.Raw,
    Pipedream.UpdateAppOverrideOpts
> = core.serialization.object({
    name: core.serialization.string().optional(),
    oauthAppId: core.serialization.property("oauth_app_id", core.serialization.string().optional()),
    cfmap: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
});

export declare namespace UpdateAppOverrideOpts {
    export interface Raw {
        name?: string | null;
        oauth_app_id?: string | null;
        cfmap?: Record<string, unknown> | null;
    }
}
