// This file was auto-generated by Fern from our API Definition.

export const ListComponentsRequestRegistry = {
    Public: "public",
    Private: "private",
    All: "all",
} as const;
export type ListComponentsRequestRegistry =
    (typeof ListComponentsRequestRegistry)[keyof typeof ListComponentsRequestRegistry];
