// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         url: "url"
 *     }
 */
export interface SetWebhookOpts {
    /** The webhook URL to set */
    url: string;
}
