// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id"
 *     }
 */
export interface ListActionsRequest {
    /** The project ID, which starts with 'proj_'. */
    projectId: string;
    /** The cursor to start from for pagination */
    after?: string;
    /** The cursor to end before for pagination */
    before?: string;
    /** The maximum number of results to return */
    limit?: number;
    /** A search query to filter the actions */
    q?: string;
    /** The ID or name slug of the app to filter the actions */
    app?: string;
}
