// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         externalUserId: "external_user_id",
 *         oauthAppId: "oauth_app_id",
 *         appSlug: "app_slug",
 *         cfmapJson: "cfmap_json",
 *         connectToken: "connect_token"
 *     }
 */
export interface CreateAccountOpts {
    externalUserId?: string;
    /** The OAuth app ID to filter by, if applicable */
    oauthAppId?: string;
    /** The app slug for the account */
    appSlug: string;
    /** JSON string containing the custom fields mapping */
    cfmapJson: string;
    /** The connect token for authentication */
    connectToken: string;
    /** Optional name for the account */
    name?: string;
    /** An existing account ID to reconnect. When provided, the account's credentials are updated instead of creating a new account. Must belong to the same external user and project environment as the connect token, and match the app identified by app_slug. */
    accountId?: string;
}
