/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         appSlug: "app_slug",
 *         cfmapJson: "cfmap_json",
 *         connectToken: "connect_token"
 *     }
 */
export interface CreateAccountOpts {
    /** The app slug or ID to filter accounts by. */
    appId?: string;
    externalUserId?: string;
    /** The OAuth app ID to filter by, if applicable */
    oauthAppId?: string;
    /** The app slug for the account */
    appSlug: string;
    /** JSON string containing the custom fields mapping */
    cfmapJson: string;
    /** The connect token for authentication */
    connectToken: string;
    /** Optional name for the account */
    name?: string;
}
