// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id"
 *     }
 */
export interface DeleteProjectsRequest {
    /** The project ID, which starts with `proj_`. */
    projectId: string;
}
