// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {}
 */
export interface UpdateProjectOpts {
    /** Name of the project */
    name?: string;
    /** Display name for the Connect application */
    appName?: string;
    /** Support email displayed to end users */
    supportEmail?: string;
    /** External URL for the project, if configured */
    externalUrl?: string;
}
