// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         logo: "data:image/png;base64,AAAAAA..."
 *     }
 */
export interface UpdateProjectLogoOpts {
    /** The project ID, which starts with `proj_`. */
    projectId: string;
    /** Data URI containing the new Base64 encoded image */
    logo: string;
}
