// This file was auto-generated by Fern from our API Definition.

export const ListTriggersRequestRegistry = {
    Public: "public",
    Private: "private",
    All: "all",
} as const;
export type ListTriggersRequestRegistry =
    (typeof ListTriggersRequestRegistry)[keyof typeof ListTriggersRequestRegistry];
