// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../index.js";

/**
 * @example
 *     {}
 */
export interface ListAppsRequest {
    /** The cursor to start from for pagination */
    after?: string;
    /** The cursor to end before for pagination */
    before?: string;
    /** The maximum number of results to return */
    limit?: number;
    /** A search query to filter the apps */
    q?: string;
    /** The key to sort the apps by */
    sortKey?: Pipedream.ListAppsRequestSortKey;
    /** The direction to sort the apps */
    sortDirection?: Pipedream.ListAppsRequestSortDirection;
    /** Only return apps in these categories */
    categoryIds?: string | string[];
}
