/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Response object for a Pipedream app's metadata
 */
export interface App {
    /** ID of the app. Only applies for OAuth apps. */
    id?: string;
    /** The name slug of the target app (see https://pipedream.com/docs/connect/quickstart#find-your-apps-name-slug) */
    nameSlug: string;
    /** The human-readable name of the app */
    name: string;
    /** The authentication type used by the app */
    authType?: App.AuthType;
    /** A short description of the app */
    description?: string;
    /** The URL to the app's logo */
    imgSrc: string;
    /** A JSON string representing the custom fields for the app */
    customFieldsJson?: string;
    /** Categories associated with the app */
    categories: string[];
    /** A rough directional ordering of app popularity, subject to changes by Pipedream */
    featuredWeight: number;
}

export namespace App {
    /**
     * The authentication type used by the app
     */
    export type AuthType = "keys" | "oauth" | "none";
    export const AuthType = {
        Keys: "keys",
        Oauth: "oauth",
        None: "none",
    } as const;
}
