/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Indicates if a File Stash ID is optional or required to run the component
 */
export type ComponentStash = "optional" | "required";
export const ComponentStash = {
    Optional: "optional",
    Required: "required",
} as const;
