// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ComponentsListResponse {
    data: Pipedream.ComponentDocument[];
    pageInfo: Pipedream.ComponentsPageInfo;
}
