// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Facets response envelope: `{ "data": { <field>: [{value, count}, ...] } }`,
 * keyed by facet field name (`component_type`, `app_name_slug`). Reuses the
 * shared `FacetValue` bucket registered by the apps handler.
 */
export interface ComponentsFacetsResponse {
    data: Record<string, Pipedream.FacetValue[]>;
}
