// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropApp extends Pipedream.ConfigurablePropBase {
    /** The name slug of the app, e.g. 'github', 'slack', etc. This is used to identify the app for which the account is being configured. */
    app: string;
}
