// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropIntegerArray extends Pipedream.ConfigurablePropBase {
    /** The minimum value for integers in this array */
    min?: number;
    /** The maximum value for integers in this array */
    max?: number;
    /** Default array of integers */
    default?: Pipedream.ConfiguredPropValueInteger[];
    /** Available options for the integer array */
    options?: Pipedream.ConfigurablePropIntegerArrayOptionsItem[];
}
