// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export type ConfigurablePropBooleanOptionsItem =
    | Pipedream.PropOption
    | Pipedream.PropOptionNested
    | Pipedream.PropOptionValue
    | undefined;
