// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropAirtableBaseId extends Pipedream.ConfigurablePropBase {
    /** The name of the app prop that provides Airtable authentication */
    appProp: string;
}
