// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * The configured properties of the component
 */
export type ConfiguredProps = Record<string, Pipedream.ConfiguredPropValue>;
