// This file was auto-generated by Fern from our API Definition.

export const ConfigurablePropDiscordType = {
    DiscordChannel: "$.discord.channel",
} as const;
export type ConfigurablePropDiscordType =
    (typeof ConfigurablePropDiscordType)[keyof typeof ConfigurablePropDiscordType];
