// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropHttpRequest extends Pipedream.ConfigurablePropBase {
    default?: Pipedream.HttpRequestConfig;
}
