// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropTimer extends Pipedream.ConfigurablePropBase {
    static?: Pipedream.ConfigurablePropTimerStatic;
    default?: Pipedream.ConfigurablePropTimerDefault;
    /** Available timer configuration options */
    options?: (Pipedream.ConfigurablePropTimerOption | undefined)[];
}
