// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropDir extends Pipedream.ConfigurablePropBase {
    accessMode?: Pipedream.ConfigurablePropDirAccessMode;
    /** If true, the component's /tmp directory is synchronized with File Stash */
    sync?: boolean;
}
