// This file was auto-generated by Fern from our API Definition.

/** The mode in which the component may access File Stash */
export const ConfigurablePropDirAccessMode = {
    Read: "read",
    Write: "write",
    ReadWrite: "read-write",
} as const;
export type ConfigurablePropDirAccessMode =
    (typeof ConfigurablePropDirAccessMode)[keyof typeof ConfigurablePropDirAccessMode];
