// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface ConfigurablePropAirtableFieldId extends Pipedream.ConfigurablePropBase {
    /** The name of the prop that provides the Airtable table ID */
    tableIdProp: string;
}
