// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * A configuration or input field for a component. This is a discriminated union based on the type field.
 */
export type ConfigurableProp =
    | Pipedream.ConfigurableProp.Alert
    | Pipedream.ConfigurableProp.Any
    | Pipedream.ConfigurableProp.App
    | Pipedream.ConfigurableProp.Boolean
    | Pipedream.ConfigurableProp.InterfaceTimer
    | Pipedream.ConfigurableProp.InterfaceApphook
    | Pipedream.ConfigurableProp.Integer
    | Pipedream.ConfigurableProp.InterfaceHttp
    | Pipedream.ConfigurableProp.ServiceDb
    | Pipedream.ConfigurableProp.Sql
    | Pipedream.ConfigurableProp.AirtableBaseId
    | Pipedream.ConfigurableProp.AirtableTableId
    | Pipedream.ConfigurableProp.AirtableViewId
    | Pipedream.ConfigurableProp.AirtableFieldId
    | Pipedream.ConfigurableProp.DiscordChannel
    | Pipedream.ConfigurableProp.DiscordChannel
    | Pipedream.ConfigurableProp.Integer
    | Pipedream.ConfigurableProp.Object_
    | Pipedream.ConfigurableProp.String
    | Pipedream.ConfigurableProp.String;

export namespace ConfigurableProp {
    export interface Alert extends Pipedream.ConfigurablePropAlert {
        type: "alert";
    }

    export interface Any extends Pipedream.ConfigurablePropAny {
        type: "any";
    }

    export interface App extends Pipedream.ConfigurablePropApp {
        type: "app";
    }

    export interface Boolean extends Pipedream.ConfigurablePropBoolean {
        type: "boolean";
    }

    export interface InterfaceTimer extends Pipedream.ConfigurablePropTimer {
        type: "$.interface.timer";
    }

    export interface InterfaceApphook extends Pipedream.ConfigurablePropApphook {
        type: "$.interface.apphook";
    }

    export interface Integer extends Pipedream.ConfigurablePropIntegerArray {
        type: "integer[]";
    }

    export interface InterfaceHttp extends Pipedream.ConfigurablePropHttp {
        type: "$.interface.http";
    }

    export interface ServiceDb extends Pipedream.ConfigurablePropDb {
        type: "$.service.db";
    }

    export interface Sql extends Pipedream.ConfigurablePropSql {
        type: "sql";
    }

    export interface AirtableBaseId extends Pipedream.ConfigurablePropAirtableBaseId {
        type: "$.airtable.baseId";
    }

    export interface AirtableTableId extends Pipedream.ConfigurablePropAirtableTableId {
        type: "$.airtable.tableId";
    }

    export interface AirtableViewId extends Pipedream.ConfigurablePropAirtableViewId {
        type: "$.airtable.viewId";
    }

    export interface AirtableFieldId extends Pipedream.ConfigurablePropAirtableFieldId {
        type: "$.airtable.fieldId";
    }

    export interface DiscordChannel extends Pipedream.ConfigurablePropDiscordChannel {
        type: "$.discord.channel";
    }

    export interface DiscordChannel extends Pipedream.ConfigurablePropDiscordChannelArray {
        type: "$.discord.channel[]";
    }

    export interface Integer extends Pipedream.ConfigurablePropInteger {
        type: "integer";
    }

    export interface Object_ extends Pipedream.ConfigurablePropObject {
        type: "object";
    }

    export interface String extends Pipedream.ConfigurablePropString {
        type: "string";
    }

    export interface String extends Pipedream.ConfigurablePropStringArray {
        type: "string[]";
    }
}
