// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export type ConfiguredPropValue =
    | Pipedream.ConfiguredPropValueAny
    | undefined
    | Pipedream.ConfiguredPropValueApp
    | Pipedream.ConfiguredPropValueBoolean
    | Pipedream.ConfiguredPropValueInteger
    | Pipedream.ConfiguredPropValueObject
    | Pipedream.ConfiguredPropValueSql
    | Pipedream.ConfiguredPropValueString
    | Pipedream.ConfiguredPropValueStringArray;
