/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ConfigurablePropType =
    | "app"
    | "$.interface.apphook"
    | "$.interface.http"
    | "$.interface.timer"
    | "data_store"
    | "$.service.db"
    | "boolean"
    | "integer"
    | "object"
    | "any"
    | "string"
    | "$.airtable.baseId"
    | "$.airtable.tableId"
    | "$.airtable.viewId"
    | "$.airtable.fieldId"
    | "$.discord.channel"
    | "http_request"
    | "sql"
    | "alert"
    | "dir";
export const ConfigurablePropType = {
    App: "app",
    InterfaceApphook: "$.interface.apphook",
    InterfaceHttp: "$.interface.http",
    InterfaceTimer: "$.interface.timer",
    DataStore: "data_store",
    ServiceDb: "$.service.db",
    Boolean: "boolean",
    Integer: "integer",
    Object: "object",
    Any: "any",
    String: "string",
    AirtableBaseId: "$.airtable.baseId",
    AirtableTableId: "$.airtable.tableId",
    AirtableViewId: "$.airtable.viewId",
    AirtableFieldId: "$.airtable.fieldId",
    DiscordChannel: "$.discord.channel",
    HttpRequest: "http_request",
    Sql: "sql",
    Alert: "alert",
    Dir: "dir",
} as const;
