/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Options for creating a Connect token
 */
export interface ConnectTokenCreateOpts {
    /** Your end user ID, for whom you're creating the token */
    externalUserId: string;
    /** List of allowed origins for CORS */
    allowedOrigins?: string[];
    /** URI to redirect to on error */
    errorRedirectUri?: string;
    /** URI to redirect to on success */
    successRedirectUri?: string;
    /** Webhook URI for notifications */
    webhookUri?: string;
}
