// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * A component/interface that emits events
 */
export type Emitter = Pipedream.DeployedComponent | Pipedream.HttpInterface | Pipedream.TimerInterface;
