/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * A component/interface that emits events
 */
export type Emitter =
    | Pipedream.Emitter.DeployedComponent
    | Pipedream.Emitter.HttpInterface
    | Pipedream.Emitter.TimerInterface;

export namespace Emitter {
    export interface DeployedComponent extends Pipedream.DeployedComponent {
        type: "DeployedComponent";
    }

    export interface HttpInterface extends Pipedream.HttpInterface {
        type: "HttpInterface";
    }

    export interface TimerInterface extends Pipedream.TimerInterface {
        type: "TimerInterface";
    }
}
