// This file was auto-generated by Fern from our API Definition.

export interface ExternalUser {
    /** The external user's Pipedream ID */
    id: string;
    /** Your identifier for the external user */
    externalId: string;
    createdAt?: Date;
    updatedAt?: Date;
}
