// This file was auto-generated by Fern from our API Definition.

/**
 * One facet bucket: a field value and how many apps carry it.
 */
export interface FacetValue {
    count: number;
    value: string;
}
