// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Response received when retrieving a list of components
 */
export interface GetComponentsResponse {
    data: Pipedream.Component[];
    pageInfo: Pipedream.PageInfo;
}
