// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Response received when retrieving trigger events
 */
export interface GetTriggerEventsResponse {
    data: Pipedream.EmittedEvent[];
}
