// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

export interface GetUsersResponse {
    data: Pipedream.ExternalUser[];
    pageInfo: Pipedream.PageInfo;
}
