// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Response received when retrieving a webhook with its signing key
 */
export interface GetWebhookWithSigningKeyResponse {
    data: Pipedream.WebhookWithSigningKey;
}
