// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Response received when listing app categories
 */
export type ListAppCategoriesResponse = Pipedream.AppCategory[];
