// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Response received when listing custom OAuth clients
 */
export interface ListOauthAppsResponse {
    data: Pipedream.OauthApp[];
    pageInfo: Pipedream.PageInfo;
}
