/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Request options for reloading a component's props when dealing with dynamic props
 */
export interface ReloadPropsOpts {
    /** The component ID */
    id: string;
    /** The external user ID */
    externalUserId: string;
    /** Whether this operation should block until completion */
    blocking?: boolean;
    /** The configured properties for the component */
    configuredProps?: Record<string, unknown>;
    /** The ID for dynamic props */
    dynamicPropsId?: string;
}
