/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as Pipedream from "../index.js";

/**
 * Response from reloading component props
 */
export interface ReloadPropsResponse {
    /** Any logs produced during the configuration of the prop */
    observations?: Record<string, unknown>;
    /** Any errors that occurred during configuration */
    errors?: string[];
    dynamicProps?: Pipedream.DynamicProps;
}
