// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Response received when validating a connect token
 */
export interface ValidateTokenResponse {
    app?: Pipedream.App;
    /** Error message if validation failed */
    error?: string;
    /** URI to redirect to on error */
    errorRedirectUri?: string;
    /** OAuth app ID if applicable */
    oauthAppId?: string;
    /** True when the resolved OAuth client is the app's Workday-official client */
    oauthAppWorkdayOfficial?: boolean;
    /** Name of the project app */
    projectAppName?: string;
    /** Environment of the project */
    projectEnvironment?: string;
    /** ID of the project */
    projectId?: string;
    /** Support email for the project */
    projectSupportEmail?: string;
    /** Whether the token validation was successful */
    success: boolean;
    /** URI to redirect to on success */
    successRedirectUri?: string;
}
