// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * Current outbound delivery lifecycle and bounded diagnostic evidence
 */
export interface WebhookDeliveryState {
    state: Pipedream.WebhookDeliveryStateState;
    /** Time the current state began, in epoch seconds */
    since?: number;
    lastError?: string;
    consecutiveFailures: number;
    sheds: number;
}
