// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../index.js";

/**
 * A webhook object including the signing key
 */
export interface WebhookWithSigningKey {
    /** The unique ID of the webhook */
    id: string;
    /** The webhook URL */
    url: string;
    /** The webhook signing key */
    signingKey: string;
    /** Whether a signing key has been set for this webhook */
    signingKeySet: boolean;
    active?: boolean;
    deliveryBackend?: Pipedream.WebhookWithSigningKeyDeliveryBackend;
    deliveryState?: Pipedream.WebhookDeliveryState;
    /** The time the webhook was created, in epoch seconds */
    createdAt: number;
    /** The time the webhook was last updated, in epoch seconds */
    updatedAt: number;
}
