// This file was auto-generated by Fern from our API Definition.

export const WebhookDeliveryStateState = {
    Happy: "happy",
    Penalty: "penalty",
    LifeSupport: "life_support",
    Deactivated: "deactivated",
} as const;
export type WebhookDeliveryStateState = (typeof WebhookDeliveryStateState)[keyof typeof WebhookDeliveryStateState];
