// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import type * as serializers from "../../../../index.js";

export const CreateOauthAppOpts: core.serialization.Schema<
    serializers.CreateOauthAppOpts.Raw,
    Pipedream.CreateOauthAppOpts
> = core.serialization.object({
    app: core.serialization.string(),
    clientId: core.serialization.property("client_id", core.serialization.string().optional()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    scopes: core.serialization.list(core.serialization.string()).optional(),
    additionalScopes: core.serialization.property(
        "additional_scopes",
        core.serialization.list(core.serialization.string()).optional(),
    ),
});

export declare namespace CreateOauthAppOpts {
    export interface Raw {
        app: string;
        client_id?: string | null;
        client_secret?: string | null;
        name?: string | null;
        description?: string | null;
        scopes?: string[] | null;
        additional_scopes?: string[] | null;
    }
}
