/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";
import { ConfiguredProp } from "../../../../types/ConfiguredProp.js";
import { RunActionOptsStashId } from "../../../../types/RunActionOptsStashId.js";
import { ConfiguredPropValue } from "../../../../types/ConfiguredPropValue.js";

export const RunActionOpts: core.serialization.Schema<serializers.RunActionOpts.Raw, Pipedream.RunActionOpts> =
    core.serialization.object({
        id: core.serialization.string(),
        externalUserId: core.serialization.property("external_user_id", core.serialization.string()),
        configuredProps: core.serialization.property("configured_props", ConfiguredProp.optional()),
        dynamicPropsId: core.serialization.property("dynamic_props_id", core.serialization.string().optional()),
        stashId: core.serialization.property("stash_id", RunActionOptsStashId.optional()),
    });

export declare namespace RunActionOpts {
    export interface Raw {
        id: string;
        external_user_id: string;
        configured_props?: ConfiguredProp.Raw | null;
        dynamic_props_id?: string | null;
        stash_id?: RunActionOptsStashId.Raw | null;
    }
}
