/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";

export const RunActionOpts: core.serialization.Schema<
    serializers.RunActionOpts.Raw,
    Omit<Pipedream.RunActionOpts, "asyncHandle">
> = core.serialization.object({
    id: core.serialization.string(),
    externalUserId: core.serialization.property("external_user_id", core.serialization.string()),
    configuredProps: core.serialization.property(
        "configured_props",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    dynamicPropsId: core.serialization.property("dynamic_props_id", core.serialization.string().optional()),
});

export declare namespace RunActionOpts {
    export interface Raw {
        id: string;
        external_user_id: string;
        configured_props?: Record<string, unknown> | null;
        dynamic_props_id?: string | null;
    }
}
