/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../index.js";
import * as Pipedream from "../../../../../api/index.js";
import * as core from "../../../../../core/index.js";

export const CreateOAuthTokenOpts: core.serialization.Schema<
    serializers.CreateOAuthTokenOpts.Raw,
    Pipedream.CreateOAuthTokenOpts
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string()),
});

export declare namespace CreateOAuthTokenOpts {
    export interface Raw {
        client_id: string;
        client_secret: string;
    }
}
