// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AccountId: core.serialization.Schema<serializers.AccountId.Raw, Pipedream.AccountId> =
    core.serialization.string();

export declare namespace AccountId {
    export type Raw = string;
}
