/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { AppAuthType } from "./AppAuthType.js";

export const App: core.serialization.ObjectSchema<serializers.App.Raw, Pipedream.App> = core.serialization.object({
    id: core.serialization.string().optional(),
    nameSlug: core.serialization.property("name_slug", core.serialization.string()),
    name: core.serialization.string(),
    authType: core.serialization.property("auth_type", AppAuthType.optional()),
    description: core.serialization.string().optional(),
    imgSrc: core.serialization.property("img_src", core.serialization.string()),
    customFieldsJson: core.serialization.property("custom_fields_json", core.serialization.string().optional()),
    categories: core.serialization.list(core.serialization.string()),
    featuredWeight: core.serialization.property("featured_weight", core.serialization.number()),
});

export declare namespace App {
    export interface Raw {
        id?: string | null;
        name_slug: string;
        name: string;
        auth_type?: AppAuthType.Raw | null;
        description?: string | null;
        img_src: string;
        custom_fields_json?: string | null;
        categories: string[];
        featured_weight: number;
    }
}
