// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const AppDocument: core.serialization.ObjectSchema<serializers.AppDocument.Raw, Pipedream.AppDocument> =
    core.serialization.object({
        authType: core.serialization.property("auth_type", core.serialization.string().optional()),
        categoryName: core.serialization.property("category_name", core.serialization.string().optional()),
        description: core.serialization.string().optional(),
        featuredWeight: core.serialization.property("featured_weight", core.serialization.number()),
        hasActions: core.serialization.property("has_actions", core.serialization.boolean()),
        hasTriggers: core.serialization.property("has_triggers", core.serialization.boolean()),
        id: core.serialization.string(),
        imgSrc: core.serialization.property("img_src", core.serialization.string()),
        name: core.serialization.string(),
        nameSlug: core.serialization.property("name_slug", core.serialization.string()),
    });

export declare namespace AppDocument {
    export interface Raw {
        auth_type?: string | null;
        category_name?: string | null;
        description?: string | null;
        featured_weight: number;
        has_actions: boolean;
        has_triggers: boolean;
        id: string;
        img_src: string;
        name: string;
        name_slug: string;
    }
}
