// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { App } from "./App.js";

export const AppOverride: core.serialization.ObjectSchema<serializers.AppOverride.Raw, Pipedream.AppOverride> =
    core.serialization.object({
        id: core.serialization.string(),
        name: core.serialization.string(),
        app: App,
        oauthAppId: core.serialization.property("oauth_app_id", core.serialization.string().optional()),
        cfmap: core.serialization.record(core.serialization.string(), core.serialization.unknown()),
        ownerId: core.serialization.property("owner_id", core.serialization.string()),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
    });

export declare namespace AppOverride {
    export interface Raw {
        id: string;
        name: string;
        app: App.Raw;
        oauth_app_id?: string | null;
        cfmap: Record<string, unknown>;
        owner_id: string;
        created_at?: string | null;
        updated_at?: string | null;
    }
}
