// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AppDocument } from "./AppDocument.js";

export const AppResponse: core.serialization.ObjectSchema<serializers.AppResponse.Raw, Pipedream.AppResponse> =
    core.serialization.object({
        data: AppDocument,
    });

export declare namespace AppResponse {
    export interface Raw {
        data: AppDocument.Raw;
    }
}
