// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const BackendClientOpts: core.serialization.ObjectSchema<
    serializers.BackendClientOpts.Raw,
    Pipedream.BackendClientOpts
> = core.serialization.object({
    clientId: core.serialization.property("client_id", core.serialization.string().optional()),
    clientSecret: core.serialization.property("client_secret", core.serialization.string().optional()),
    apiUrl: core.serialization.property("api_url", core.serialization.string().optional()),
    scope: core.serialization.string().optional(),
});

export declare namespace BackendClientOpts {
    export interface Raw {
        client_id?: string | null;
        client_secret?: string | null;
        api_url?: string | null;
        scope?: string | null;
    }
}
