// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ComponentType: core.serialization.Schema<serializers.ComponentType.Raw, Pipedream.ComponentType> =
    core.serialization.enum_(["trigger", "action"]);

export declare namespace ComponentType {
    export type Raw = "trigger" | "action";
}
