/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ComponentStash: core.serialization.Schema<serializers.ComponentStash.Raw, Pipedream.ComponentStash> =
    core.serialization.enum_(["optional", "required"]);

export declare namespace ComponentStash {
    export type Raw = "optional" | "required";
}
