// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ComponentDocument: core.serialization.ObjectSchema<
    serializers.ComponentDocument.Raw,
    Pipedream.ComponentDocument
> = core.serialization.object({
    appNameSlug: core.serialization.property("app_name_slug", core.serialization.string().optional()),
    componentType: core.serialization.property("component_type", core.serialization.string().optional()),
    description: core.serialization.string().optional(),
    id: core.serialization.string(),
    key: core.serialization.string(),
    name: core.serialization.string().optional(),
    version: core.serialization.string().optional(),
});

export declare namespace ComponentDocument {
    export interface Raw {
        app_name_slug?: string | null;
        component_type?: string | null;
        description?: string | null;
        id: string;
        key: string;
        name?: string | null;
        version?: string | null;
    }
}
