/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ConfigurableProp } from "./ConfigurableProp.js";
import { ComponentStash } from "./ComponentStash.js";

export const Component: core.serialization.ObjectSchema<serializers.Component.Raw, Pipedream.Component> =
    core.serialization.object({
        key: core.serialization.string(),
        name: core.serialization.string(),
        version: core.serialization.string(),
        configurableProps: core.serialization.property("configurable_props", core.serialization.list(ConfigurableProp)),
        description: core.serialization.string().optional(),
        componentType: core.serialization.property("component_type", core.serialization.string().optional()),
        stash: ComponentStash.optional(),
    });

export declare namespace Component {
    export interface Raw {
        key: string;
        name: string;
        version: string;
        configurable_props: ConfigurableProp.Raw[];
        description?: string | null;
        component_type?: string | null;
        stash?: ComponentStash.Raw | null;
    }
}
