// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { FacetValue } from "./FacetValue.js";

export const ComponentsFacetsResponse: core.serialization.ObjectSchema<
    serializers.ComponentsFacetsResponse.Raw,
    Pipedream.ComponentsFacetsResponse
> = core.serialization.object({
    data: core.serialization.record(core.serialization.string(), core.serialization.list(FacetValue)),
});

export declare namespace ComponentsFacetsResponse {
    export interface Raw {
        data: Record<string, FacetValue.Raw[]>;
    }
}
