// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropAlertType } from "./ConfigurablePropAlertType.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";

export const ConfigurablePropAlert: core.serialization.ObjectSchema<
    serializers.ConfigurablePropAlert.Raw,
    Pipedream.ConfigurablePropAlert
> = core.serialization
    .object({
        alertType: ConfigurablePropAlertType.optional(),
        content: core.serialization.string(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropAlert {
    export interface Raw extends ConfigurablePropBase.Raw {
        alertType?: ConfigurablePropAlertType.Raw | null;
        content: string;
    }
}
