/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfigurablePropAlertType: core.serialization.Schema<
    serializers.ConfigurablePropAlertType.Raw,
    Pipedream.ConfigurablePropAlertType
> = core.serialization.enum_(["info", "neutral", "warning", "error"]);

export declare namespace ConfigurablePropAlertType {
    export type Raw = "info" | "neutral" | "warning" | "error";
}
