/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfiguredPropValueInteger: core.serialization.Schema<
    serializers.ConfiguredPropValueInteger.Raw,
    Pipedream.ConfiguredPropValueInteger
> = core.serialization.number();

export declare namespace ConfiguredPropValueInteger {
    export type Raw = number;
}
