// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";

export const ConfigurablePropDiscordChannelArray: core.serialization.ObjectSchema<
    serializers.ConfigurablePropDiscordChannelArray.Raw,
    Pipedream.ConfigurablePropDiscordChannelArray
> = core.serialization
    .object({
        appProp: core.serialization.string().optional(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropDiscordChannelArray {
    export interface Raw extends ConfigurablePropBase.Raw {
        appProp?: string | null;
    }
}
