// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConfigurablePropDiscordChannelArray: core.serialization.ObjectSchema<
    serializers.ConfigurablePropDiscordChannelArray.Raw,
    Pipedream.ConfigurablePropDiscordChannelArray
> = core.serialization.object({
    type: core.serialization.stringLiteral("$.discord.channel[]"),
    appProp: core.serialization.string().optional(),
    name: core.serialization.string(),
    label: core.serialization.string().optionalNullable(),
    description: core.serialization.string().optionalNullable(),
    optional: core.serialization.boolean().optionalNullable(),
    disabled: core.serialization.boolean().optionalNullable(),
    hidden: core.serialization.boolean().optionalNullable(),
    remoteOptions: core.serialization.boolean().optionalNullable(),
    useQuery: core.serialization.boolean().optionalNullable(),
    reloadProps: core.serialization.boolean().optionalNullable(),
    withLabel: core.serialization.boolean().optionalNullable(),
});

export declare namespace ConfigurablePropDiscordChannelArray {
    export interface Raw {
        type: "$.discord.channel[]";
        appProp?: string | null;
        name: string;
        label?: (string | null | undefined) | null;
        description?: (string | null | undefined) | null;
        optional?: (boolean | null | undefined) | null;
        disabled?: (boolean | null | undefined) | null;
        hidden?: (boolean | null | undefined) | null;
        remoteOptions?: (boolean | null | undefined) | null;
        useQuery?: (boolean | null | undefined) | null;
        reloadProps?: (boolean | null | undefined) | null;
        withLabel?: (boolean | null | undefined) | null;
    }
}
