/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfiguredPropValueBoolean: core.serialization.Schema<
    serializers.ConfiguredPropValueBoolean.Raw,
    Pipedream.ConfiguredPropValueBoolean
> = core.serialization.boolean();

export declare namespace ConfiguredPropValueBoolean {
    export type Raw = boolean;
}
