/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ConfigurePropOptionItem } from "./ConfigurePropOptionItem.js";

export const ConfigurePropOption: core.serialization.Schema<
    serializers.ConfigurePropOption.Raw,
    Pipedream.ConfigurePropOption
> = core.serialization.list(ConfigurePropOptionItem).optional();

export declare namespace ConfigurePropOption {
    export type Raw = ConfigurePropOptionItem.Raw[] | null | undefined;
}
