/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfigurablePropString: core.serialization.ObjectSchema<
    serializers.ConfigurablePropString.Raw,
    Pipedream.ConfigurablePropString
> = core.serialization.object({
    type: core.serialization.stringLiteral("string").optional(),
    secret: core.serialization.boolean().optional(),
    name: core.serialization.string(),
    label: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    optional: core.serialization.boolean().optional(),
    disabled: core.serialization.boolean().optional(),
    hidden: core.serialization.boolean().optional(),
    remoteOptions: core.serialization.boolean().optional(),
    useQuery: core.serialization.boolean().optional(),
    reloadProps: core.serialization.boolean().optional(),
    withLabel: core.serialization.boolean().optional(),
});

export declare namespace ConfigurablePropString {
    export interface Raw {
        type?: "string" | null;
        secret?: boolean | null;
        name: string;
        label?: string | null;
        description?: string | null;
        optional?: boolean | null;
        disabled?: boolean | null;
        hidden?: boolean | null;
        remoteOptions?: boolean | null;
        useQuery?: boolean | null;
        reloadProps?: boolean | null;
        withLabel?: boolean | null;
    }
}
