/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfiguredPropSql: core.serialization.ObjectSchema<
    serializers.ConfiguredPropSql.Raw,
    Pipedream.ConfiguredPropSql
> = core.serialization.object({
    value: core.serialization.string().optional(),
    query: core.serialization.string().optional(),
    params: core.serialization.list(core.serialization.string()).optional(),
    usePreparedStatements: core.serialization.boolean().optional(),
});

export declare namespace ConfiguredPropSql {
    export interface Raw {
        value?: string | null;
        query?: string | null;
        params?: string[] | null;
        usePreparedStatements?: boolean | null;
    }
}
