// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConfigurablePropDirAccessMode: core.serialization.Schema<
    serializers.ConfigurablePropDirAccessMode.Raw,
    Pipedream.ConfigurablePropDirAccessMode
> = core.serialization.enum_(["read", "write", "read-write"]);

export declare namespace ConfigurablePropDirAccessMode {
    export type Raw = "read" | "write" | "read-write";
}
