// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";

export const ConfigurablePropDiscord: core.serialization.ObjectSchema<
    serializers.ConfigurablePropDiscord.Raw,
    Pipedream.ConfigurablePropDiscord
> = core.serialization
    .object({
        type: core.serialization.stringLiteral("$.discord.channel"),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropDiscord {
    export interface Raw extends ConfigurablePropBase.Raw {
        type: "$.discord.channel";
    }
}
