// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConfigurablePropType: core.serialization.Schema<
    serializers.ConfigurablePropType.Raw,
    Pipedream.ConfigurablePropType
> = core.serialization.enum_([
    "$.airtable.baseId",
    "$.airtable.fieldId",
    "$.airtable.tableId",
    "$.airtable.viewId",
    "$.discord.channel",
    "$.discord.channel[]",
    "$.interface.apphook",
    "$.interface.http",
    "$.interface.timer",
    "$.service.db",
    "alert",
    "any",
    "app",
    "boolean",
    "data_store",
    "dir",
    "http_request",
    "integer",
    "integer[]",
    "object",
    "sql",
    "string",
    "string[]",
]);

export declare namespace ConfigurablePropType {
    export type Raw =
        | "$.airtable.baseId"
        | "$.airtable.fieldId"
        | "$.airtable.tableId"
        | "$.airtable.viewId"
        | "$.discord.channel"
        | "$.discord.channel[]"
        | "$.interface.apphook"
        | "$.interface.http"
        | "$.interface.timer"
        | "$.service.db"
        | "alert"
        | "any"
        | "app"
        | "boolean"
        | "data_store"
        | "dir"
        | "http_request"
        | "integer"
        | "integer[]"
        | "object"
        | "sql"
        | "string"
        | "string[]";
}
