// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBooleanOptionsItem } from "./ConfigurablePropBooleanOptionsItem.js";
import { ConfiguredPropValueBoolean } from "./ConfiguredPropValueBoolean.js";

export const ConfigurablePropBoolean: core.serialization.ObjectSchema<
    serializers.ConfigurablePropBoolean.Raw,
    Pipedream.ConfigurablePropBoolean
> = core.serialization.object({
    type: core.serialization.stringLiteral("boolean"),
    default: ConfiguredPropValueBoolean.optional(),
    options: core.serialization.list(ConfigurablePropBooleanOptionsItem).optional(),
    name: core.serialization.string(),
    label: core.serialization.string().optionalNullable(),
    description: core.serialization.string().optionalNullable(),
    optional: core.serialization.boolean().optionalNullable(),
    disabled: core.serialization.boolean().optionalNullable(),
    hidden: core.serialization.boolean().optionalNullable(),
    remoteOptions: core.serialization.boolean().optionalNullable(),
    useQuery: core.serialization.boolean().optionalNullable(),
    reloadProps: core.serialization.boolean().optionalNullable(),
    withLabel: core.serialization.boolean().optionalNullable(),
});

export declare namespace ConfigurablePropBoolean {
    export interface Raw {
        type: "boolean";
        default?: ConfiguredPropValueBoolean.Raw | null;
        options?: ConfigurablePropBooleanOptionsItem.Raw[] | null;
        name: string;
        label?: (string | null | undefined) | null;
        description?: (string | null | undefined) | null;
        optional?: (boolean | null | undefined) | null;
        disabled?: (boolean | null | undefined) | null;
        hidden?: (boolean | null | undefined) | null;
        remoteOptions?: (boolean | null | undefined) | null;
        useQuery?: (boolean | null | undefined) | null;
        reloadProps?: (boolean | null | undefined) | null;
        withLabel?: (boolean | null | undefined) | null;
    }
}
