// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurePropOptionsItem } from "./ConfigurePropOptionsItem.js";

export const ConfigurePropOptions: core.serialization.Schema<
    serializers.ConfigurePropOptions.Raw,
    Pipedream.ConfigurePropOptions
> = core.serialization.list(ConfigurePropOptionsItem).nullable();

export declare namespace ConfigurePropOptions {
    export type Raw = ConfigurePropOptionsItem.Raw[] | null | undefined;
}
