// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConfigurablePropAirtableFieldId: core.serialization.ObjectSchema<
    serializers.ConfigurablePropAirtableFieldId.Raw,
    Pipedream.ConfigurablePropAirtableFieldId
> = core.serialization.object({
    type: core.serialization.stringLiteral("$.airtable.fieldId"),
    tableIdProp: core.serialization.string(),
    name: core.serialization.string(),
    label: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    optional: core.serialization.boolean().optional(),
    disabled: core.serialization.boolean().optional(),
    hidden: core.serialization.boolean().optional(),
    remoteOptions: core.serialization.boolean().optional(),
    useQuery: core.serialization.boolean().optional(),
    reloadProps: core.serialization.boolean().optional(),
    withLabel: core.serialization.boolean().optional(),
});

export declare namespace ConfigurablePropAirtableFieldId {
    export interface Raw {
        type: "$.airtable.fieldId";
        tableIdProp: string;
        name: string;
        label?: string | null;
        description?: string | null;
        optional?: boolean | null;
        disabled?: boolean | null;
        hidden?: boolean | null;
        remoteOptions?: boolean | null;
        useQuery?: boolean | null;
        reloadProps?: boolean | null;
        withLabel?: boolean | null;
    }
}
