// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropAnyOptionsItem } from "./ConfigurablePropAnyOptionsItem.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";
import { ConfiguredPropValueAny } from "./ConfiguredPropValueAny.js";

export const ConfigurablePropAny: core.serialization.ObjectSchema<
    serializers.ConfigurablePropAny.Raw,
    Pipedream.ConfigurablePropAny
> = core.serialization
    .object({
        default: ConfiguredPropValueAny.optional(),
        options: core.serialization.list(ConfigurablePropAnyOptionsItem).optional(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropAny {
    export interface Raw extends ConfigurablePropBase.Raw {
        default?: (ConfiguredPropValueAny.Raw | undefined) | null;
        options?: ConfigurablePropAnyOptionsItem.Raw[] | null;
    }
}
