/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ConfiguredPropsValue } from "./ConfiguredPropsValue.js";

export const ConfiguredProps: core.serialization.Schema<serializers.ConfiguredProps.Raw, Pipedream.ConfiguredProps> =
    core.serialization.record(core.serialization.string(), ConfiguredPropsValue);

export declare namespace ConfiguredProps {
    export type Raw = Record<string, ConfiguredPropsValue.Raw>;
}
