// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConfigurablePropDiscordType: core.serialization.Schema<
    serializers.ConfigurablePropDiscordType.Raw,
    Pipedream.ConfigurablePropDiscordType
> = core.serialization.enum_(["$.discord.channel"]);

export declare namespace ConfigurablePropDiscordType {
    export type Raw = "$.discord.channel";
}
