// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PropOption } from "./PropOption.js";
import { PropOptionNested } from "./PropOptionNested.js";
import { PropOptionValue } from "./PropOptionValue.js";

export const ConfigurablePropIntegerArrayOptionsItem: core.serialization.Schema<
    serializers.ConfigurablePropIntegerArrayOptionsItem.Raw,
    Pipedream.ConfigurablePropIntegerArrayOptionsItem
> = core.serialization.undiscriminatedUnion([PropOption, PropOptionNested, PropOptionValue.optional()]);

export declare namespace ConfigurablePropIntegerArrayOptionsItem {
    export type Raw = PropOption.Raw | PropOptionNested.Raw | (PropOptionValue.Raw | null | undefined);
}
