// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { TimerCron } from "./TimerCron.js";
import { TimerInterval } from "./TimerInterval.js";

export const ConfigurablePropTimerStatic: core.serialization.Schema<
    serializers.ConfigurablePropTimerStatic.Raw,
    Pipedream.ConfigurablePropTimerStatic
> = core.serialization.undiscriminatedUnion([TimerInterval, TimerCron]);

export declare namespace ConfigurablePropTimerStatic {
    export type Raw = TimerInterval.Raw | TimerCron.Raw;
}
