// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";

export const ConfigurablePropDiscordChannel: core.serialization.ObjectSchema<
    serializers.ConfigurablePropDiscordChannel.Raw,
    Pipedream.ConfigurablePropDiscordChannel
> = core.serialization
    .object({
        appProp: core.serialization.string(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropDiscordChannel {
    export interface Raw extends ConfigurablePropBase.Raw {
        appProp: string;
    }
}
