// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";
import { ConfigurablePropStringArrayOptionsItem } from "./ConfigurablePropStringArrayOptionsItem.js";
import { ConfiguredPropValueString } from "./ConfiguredPropValueString.js";

export const ConfigurablePropStringArray: core.serialization.ObjectSchema<
    serializers.ConfigurablePropStringArray.Raw,
    Pipedream.ConfigurablePropStringArray
> = core.serialization
    .object({
        secret: core.serialization.boolean().optional(),
        default: core.serialization.list(ConfiguredPropValueString).optional(),
        options: core.serialization.list(ConfigurablePropStringArrayOptionsItem).optional(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropStringArray {
    export interface Raw extends ConfigurablePropBase.Raw {
        secret?: boolean | null;
        default?: ConfiguredPropValueString.Raw[] | null;
        options?: ConfigurablePropStringArrayOptionsItem.Raw[] | null;
    }
}
