/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { PropOption } from "./PropOption.js";

export const ConfigurePropResponse: core.serialization.ObjectSchema<
    serializers.ConfigurePropResponse.Raw,
    Pipedream.ConfigurePropResponse
> = core.serialization.object({
    options: core.serialization.list(PropOption).optional(),
    errors: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace ConfigurePropResponse {
    export interface Raw {
        options?: PropOption.Raw[] | null;
        errors?: string[] | null;
    }
}
