// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";
import { ConfigurablePropBooleanOptionsItem } from "./ConfigurablePropBooleanOptionsItem.js";
import { ConfiguredPropValueBoolean } from "./ConfiguredPropValueBoolean.js";

export const ConfigurablePropBoolean: core.serialization.ObjectSchema<
    serializers.ConfigurablePropBoolean.Raw,
    Pipedream.ConfigurablePropBoolean
> = core.serialization
    .object({
        default: ConfiguredPropValueBoolean.optional(),
        options: core.serialization.list(ConfigurablePropBooleanOptionsItem).optional(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropBoolean {
    export interface Raw extends ConfigurablePropBase.Raw {
        default?: ConfiguredPropValueBoolean.Raw | null;
        options?: ConfigurablePropBooleanOptionsItem.Raw[] | null;
    }
}
