/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfigurablePropInteger: core.serialization.ObjectSchema<
    serializers.ConfigurablePropInteger.Raw,
    Pipedream.ConfigurablePropInteger
> = core.serialization.object({
    type: core.serialization.stringLiteral("integer").optional(),
    min: core.serialization.number().optional(),
    max: core.serialization.number().optional(),
    name: core.serialization.string().optional(),
    label: core.serialization.string().optional(),
    description: core.serialization.string().optional(),
    optional: core.serialization.boolean().optional(),
    disabled: core.serialization.boolean().optional(),
    hidden: core.serialization.boolean().optional(),
    remoteOptions: core.serialization.boolean().optional(),
    useQuery: core.serialization.boolean().optional(),
    reloadProps: core.serialization.boolean().optional(),
    withLabel: core.serialization.boolean().optional(),
});

export declare namespace ConfigurablePropInteger {
    export interface Raw {
        type?: "integer" | null;
        min?: number | null;
        max?: number | null;
        name?: string | null;
        label?: string | null;
        description?: string | null;
        optional?: boolean | null;
        disabled?: boolean | null;
        hidden?: boolean | null;
        remoteOptions?: boolean | null;
        useQuery?: boolean | null;
        reloadProps?: boolean | null;
        withLabel?: boolean | null;
    }
}
