// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";

export const ConfigurablePropDb: core.serialization.ObjectSchema<
    serializers.ConfigurablePropDb.Raw,
    Pipedream.ConfigurablePropDb
> = core.serialization.object({}).extend(ConfigurablePropBase);

export declare namespace ConfigurablePropDb {
    export interface Raw extends ConfigurablePropBase.Raw {}
}
