// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurablePropBase } from "./ConfigurablePropBase.js";
import { ConfigurablePropStringOptionsItem } from "./ConfigurablePropStringOptionsItem.js";
import { ConfiguredPropValueString } from "./ConfiguredPropValueString.js";

export const ConfigurablePropString: core.serialization.ObjectSchema<
    serializers.ConfigurablePropString.Raw,
    Pipedream.ConfigurablePropString
> = core.serialization
    .object({
        secret: core.serialization.boolean().optional(),
        default: ConfiguredPropValueString.optional(),
        options: core.serialization.list(ConfigurablePropStringOptionsItem).optional(),
    })
    .extend(ConfigurablePropBase);

export declare namespace ConfigurablePropString {
    export interface Raw extends ConfigurablePropBase.Raw {
        secret?: boolean | null;
        default?: ConfiguredPropValueString.Raw | null;
        options?: ConfigurablePropStringOptionsItem.Raw[] | null;
    }
}
