/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ConfiguredPropValueObject: core.serialization.Schema<
    serializers.ConfiguredPropValueObject.Raw,
    Pipedream.ConfiguredPropValueObject
> = core.serialization.record(core.serialization.string(), core.serialization.unknown());

export declare namespace ConfiguredPropValueObject {
    export type Raw = Record<string, unknown>;
}
