/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ConfiguredProps } from "./ConfiguredProps.js";
import { ConfiguredPropValue } from "./ConfiguredPropValue.js";

export const ConfigurePropOpts: core.serialization.ObjectSchema<
    serializers.ConfigurePropOpts.Raw,
    Pipedream.ConfigurePropOpts
> = core.serialization.object({
    id: core.serialization.string(),
    externalUserId: core.serialization.property("external_user_id", core.serialization.string()),
    propName: core.serialization.property("prop_name", core.serialization.string()),
    blocking: core.serialization.boolean().optional(),
    configuredProps: core.serialization.property("configured_props", ConfiguredProps.optional()),
    dynamicPropsId: core.serialization.property("dynamic_props_id", core.serialization.string().optional()),
    page: core.serialization.number().optional(),
    prevContext: core.serialization.property(
        "prev_context",
        core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    ),
    query: core.serialization.string().optional(),
});

export declare namespace ConfigurePropOpts {
    export interface Raw {
        id: string;
        external_user_id: string;
        prop_name: string;
        blocking?: boolean | null;
        configured_props?: ConfiguredProps.Raw | null;
        dynamic_props_id?: string | null;
        page?: number | null;
        prev_context?: Record<string, unknown> | null;
        query?: string | null;
    }
}
