// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurePropOptions } from "./ConfigurePropOptions.js";
import { Observation } from "./Observation.js";

export const ConfigurePropResponse: core.serialization.ObjectSchema<
    serializers.ConfigurePropResponse.Raw,
    Pipedream.ConfigurePropResponse
> = core.serialization.object({
    options: ConfigurePropOptions.optional(),
    stringOptions: core.serialization.property(
        "string_options",
        core.serialization.list(core.serialization.string()).optional(),
    ),
    observations: core.serialization.list(Observation).optional(),
    context: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    errors: core.serialization.list(core.serialization.string()).optional(),
});

export declare namespace ConfigurePropResponse {
    export interface Raw {
        options?: (ConfigurePropOptions.Raw | undefined) | null;
        string_options?: string[] | null;
        observations?: Observation.Raw[] | null;
        context?: Record<string, unknown> | null;
        errors?: string[] | null;
    }
}
