// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ConnectUsage: core.serialization.ObjectSchema<serializers.ConnectUsage.Raw, Pipedream.ConnectUsage> =
    core.serialization.object({
        creditsUsed: core.serialization.property("credits_used", core.serialization.number()),
        actionRunCreditsUsed: core.serialization.property(
            "action_run_credits_used",
            core.serialization.number().optional(),
        ),
        proxyCreditsUsed: core.serialization.property("proxy_credits_used", core.serialization.number().optional()),
        sourceEmitCreditsUsed: core.serialization.property(
            "source_emit_credits_used",
            core.serialization.number().optional(),
        ),
        usageStartTs: core.serialization.property("usage_start_ts", core.serialization.number()),
        usageEndTs: core.serialization.property("usage_end_ts", core.serialization.number()),
    });

export declare namespace ConnectUsage {
    export interface Raw {
        credits_used: number;
        action_run_credits_used?: number | null;
        proxy_credits_used?: number | null;
        source_emit_credits_used?: number | null;
        usage_start_ts: number;
        usage_end_ts: number;
    }
}
