/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const CreateBrowserClientOpts: core.serialization.ObjectSchema<
    serializers.CreateBrowserClientOpts.Raw,
    Pipedream.CreateBrowserClientOpts
> = core.serialization.object({
    apiUrl: core.serialization.property("api_url", core.serialization.string().optional()),
});

export declare namespace CreateBrowserClientOpts {
    export interface Raw {
        api_url?: string | null;
    }
}
