// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConnectToken } from "./ConnectToken.js";

export const CreateTokenResponse: core.serialization.ObjectSchema<
    serializers.CreateTokenResponse.Raw,
    Pipedream.CreateTokenResponse
> = core.serialization.object({
    connectLinkUrl: core.serialization.property("connect_link_url", core.serialization.string()),
    expiresAt: core.serialization.property("expires_at", core.serialization.date()),
    token: ConnectToken,
});

export declare namespace CreateTokenResponse {
    export interface Raw {
        connect_link_url: string;
        expires_at: string;
        token: ConnectToken.Raw;
    }
}
