// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeleteTriggerOpts: core.serialization.ObjectSchema<
    serializers.DeleteTriggerOpts.Raw,
    Pipedream.DeleteTriggerOpts
> = core.serialization.object({
    ignoreHookErrors: core.serialization.property("ignore_hook_errors", core.serialization.boolean().optional()),
});

export declare namespace DeleteTriggerOpts {
    export interface Raw {
        ignore_hook_errors?: boolean | null;
    }
}
