// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const DeployTriggerResult: core.serialization.ObjectSchema<
    serializers.DeployTriggerResult.Raw,
    Pipedream.DeployTriggerResult
> = core.serialization.object({
    webhookSigningKey: core.serialization.property("webhook_signing_key", core.serialization.string().optional()),
});

export declare namespace DeployTriggerResult {
    export interface Raw {
        webhook_signing_key?: string | null;
    }
}
