/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ConfigurableProp } from "./ConfigurableProp.js";
import { ConfiguredProps } from "./ConfiguredProps.js";
import { ConfiguredPropValue } from "./ConfiguredPropValue.js";

export const DeployedComponent: core.serialization.ObjectSchema<
    serializers.DeployedComponent.Raw,
    Pipedream.DeployedComponent
> = core.serialization.object({
    id: core.serialization.string(),
    ownerId: core.serialization.property("owner_id", core.serialization.string()),
    componentId: core.serialization.property("component_id", core.serialization.string()),
    componentKey: core.serialization.property("component_key", core.serialization.string().optional()),
    configurableProps: core.serialization.property("configurable_props", core.serialization.list(ConfigurableProp)),
    configuredProps: core.serialization.property("configured_props", ConfiguredProps),
    active: core.serialization.boolean(),
    createdAt: core.serialization.property("created_at", core.serialization.number()),
    updatedAt: core.serialization.property("updated_at", core.serialization.number()),
    name: core.serialization.string(),
    nameSlug: core.serialization.property("name_slug", core.serialization.string()),
    callbackObservations: core.serialization.property("callback_observations", core.serialization.unknown().optional()),
});

export declare namespace DeployedComponent {
    export interface Raw {
        id: string;
        owner_id: string;
        component_id: string;
        component_key?: string | null;
        configurable_props: ConfigurableProp.Raw[];
        configured_props: ConfiguredProps.Raw;
        active: boolean;
        created_at: number;
        updated_at: number;
        name: string;
        name_slug: string;
        callback_observations?: unknown | null;
    }
}
