// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DeployTriggerResponseData } from "./DeployTriggerResponseData.js";

export const DeployTriggerResponse: core.serialization.ObjectSchema<
    serializers.DeployTriggerResponse.Raw,
    Pipedream.DeployTriggerResponse
> = core.serialization.object({
    data: DeployTriggerResponseData,
});

export declare namespace DeployTriggerResponse {
    export interface Raw {
        data: DeployTriggerResponseData.Raw;
    }
}
