// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ConfigurableProp } from "./ConfigurableProp.js";

export const DynamicProps: core.serialization.ObjectSchema<serializers.DynamicProps.Raw, Pipedream.DynamicProps> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        configurableProps: core.serialization.list(ConfigurableProp).optional(),
    });

export declare namespace DynamicProps {
    export interface Raw {
        id?: string | null;
        configurableProps?: ConfigurableProp.Raw[] | null;
    }
}
