// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const EmitterType: core.serialization.Schema<serializers.EmitterType.Raw, Pipedream.EmitterType> =
    core.serialization.enum_(["email", "http", "source", "timer"]);

export declare namespace EmitterType {
    export type Raw = "email" | "http" | "source" | "timer";
}
