// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, Pipedream.ErrorResponse> =
    core.serialization.object({
        error: core.serialization.string(),
        code: core.serialization.string().optional(),
        details: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    });

export declare namespace ErrorResponse {
    export interface Raw {
        error: string;
        code?: string | null;
        details?: Record<string, unknown> | null;
    }
}
