// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { App } from "./App.js";

export const GetAppResponse: core.serialization.ObjectSchema<serializers.GetAppResponse.Raw, Pipedream.GetAppResponse> =
    core.serialization.object({
        data: App,
    });

export declare namespace GetAppResponse {
    export interface Raw {
        data: App.Raw;
    }
}
