/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { Component } from "./Component.js";

export const GetComponentResponse: core.serialization.ObjectSchema<
    serializers.GetComponentResponse.Raw,
    Pipedream.GetComponentResponse
> = core.serialization.object({
    data: Component,
});

export declare namespace GetComponentResponse {
    export interface Raw {
        data: Component.Raw;
    }
}
