// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { Component } from "./Component.js";
import { PageInfo } from "./PageInfo.js";

export const GetComponentsResponse: core.serialization.ObjectSchema<
    serializers.GetComponentsResponse.Raw,
    Pipedream.GetComponentsResponse
> = core.serialization.object({
    data: core.serialization.list(Component),
    pageInfo: core.serialization.property("page_info", PageInfo),
});

export declare namespace GetComponentsResponse {
    export interface Raw {
        data: Component.Raw[];
        page_info: PageInfo.Raw;
    }
}
