/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { Emitter } from "./Emitter.js";

export const GetTriggerResponse: core.serialization.ObjectSchema<
    serializers.GetTriggerResponse.Raw,
    Pipedream.GetTriggerResponse
> = core.serialization.object({
    data: Emitter,
});

export declare namespace GetTriggerResponse {
    export interface Raw {
        data: Emitter.Raw;
    }
}
