// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { ExternalUser } from "./ExternalUser.js";
import { PageInfo } from "./PageInfo.js";

export const GetUsersResponse: core.serialization.ObjectSchema<
    serializers.GetUsersResponse.Raw,
    Pipedream.GetUsersResponse
> = core.serialization.object({
    data: core.serialization.list(ExternalUser),
    pageInfo: core.serialization.property("page_info", PageInfo),
});

export declare namespace GetUsersResponse {
    export interface Raw {
        data: ExternalUser.Raw[];
        page_info: PageInfo.Raw;
    }
}
