// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HttpRequestAuthType } from "./HttpRequestAuthType.js";

export const HttpRequestAuth: core.serialization.ObjectSchema<
    serializers.HttpRequestAuth.Raw,
    Pipedream.HttpRequestAuth
> = core.serialization.object({
    type: HttpRequestAuthType.optional(),
    username: core.serialization.string().optional(),
    password: core.serialization.string().optional(),
    token: core.serialization.string().optional(),
});

export declare namespace HttpRequestAuth {
    export interface Raw {
        type?: HttpRequestAuthType.Raw | null;
        username?: string | null;
        password?: string | null;
        token?: string | null;
    }
}
