// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HttpInterface: core.serialization.ObjectSchema<serializers.HttpInterface.Raw, Pipedream.HttpInterface> =
    core.serialization.object({
        id: core.serialization.string(),
        key: core.serialization.string(),
        endpointUrl: core.serialization.property("endpoint_url", core.serialization.string()),
        customResponse: core.serialization.property("custom_response", core.serialization.boolean()),
        createdAt: core.serialization.property("created_at", core.serialization.number()),
        updatedAt: core.serialization.property("updated_at", core.serialization.number()),
    });

export declare namespace HttpInterface {
    export interface Raw {
        id: string;
        key: string;
        endpoint_url: string;
        custom_response: boolean;
        created_at: number;
        updated_at: number;
    }
}
