// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HttpRequestField: core.serialization.ObjectSchema<
    serializers.HttpRequestField.Raw,
    Pipedream.HttpRequestField
> = core.serialization.object({
    name: core.serialization.string(),
    value: core.serialization.string(),
});

export declare namespace HttpRequestField {
    export interface Raw {
        name: string;
        value: string;
    }
}
