// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { HttpRequestBodyMode } from "./HttpRequestBodyMode.js";
import { HttpRequestBodyType } from "./HttpRequestBodyType.js";
import { HttpRequestField } from "./HttpRequestField.js";

export const HttpRequestBody: core.serialization.ObjectSchema<
    serializers.HttpRequestBody.Raw,
    Pipedream.HttpRequestBody
> = core.serialization.object({
    type: HttpRequestBodyType.optional(),
    contentType: core.serialization.string().optional(),
    fields: core.serialization.list(HttpRequestField).optional(),
    mode: HttpRequestBodyMode.optional(),
    raw: core.serialization.string().optional(),
});

export declare namespace HttpRequestBody {
    export interface Raw {
        type?: HttpRequestBodyType.Raw | null;
        contentType?: string | null;
        fields?: HttpRequestField.Raw[] | null;
        mode?: HttpRequestBodyMode.Raw | null;
        raw?: string | null;
    }
}
