// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const HttpRequestBodyMode: core.serialization.Schema<
    serializers.HttpRequestBodyMode.Raw,
    Pipedream.HttpRequestBodyMode
> = core.serialization.enum_(["fields", "raw"]);

export declare namespace HttpRequestBodyMode {
    export type Raw = "fields" | "raw";
}
