/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { AppCategory } from "./AppCategory.js";

export const ListAppCategoriesResponse: core.serialization.Schema<
    serializers.ListAppCategoriesResponse.Raw,
    Pipedream.ListAppCategoriesResponse
> = core.serialization.list(AppCategory);

export declare namespace ListAppCategoriesResponse {
    export type Raw = AppCategory.Raw[];
}
