// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { AppAuthType } from "./AppAuthType.js";
import { AppScopeProfilesItem } from "./AppScopeProfilesItem.js";

export const OauthApp: core.serialization.ObjectSchema<serializers.OauthApp.Raw, Pipedream.OauthApp> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        clientId: core.serialization.property("client_id", core.serialization.string()),
        scopes: core.serialization.list(core.serialization.string()).optional(),
        additionalScopes: core.serialization.property(
            "additional_scopes",
            core.serialization.list(core.serialization.string()).optional(),
        ),
        redirectUri: core.serialization.property("redirect_uri", core.serialization.string().optional()),
        ownerId: core.serialization.property("owner_id", core.serialization.string()),
        createdAt: core.serialization.property("created_at", core.serialization.date().optional()),
        updatedAt: core.serialization.property("updated_at", core.serialization.date().optional()),
        nameSlug: core.serialization.property("name_slug", core.serialization.string()),
        name: core.serialization.string(),
        authType: core.serialization.property("auth_type", AppAuthType.optional()),
        description: core.serialization.string().optional(),
        imgSrc: core.serialization.property("img_src", core.serialization.string()),
        customFieldsJson: core.serialization.property("custom_fields_json", core.serialization.string().optional()),
        categories: core.serialization.list(core.serialization.string()),
        featuredWeight: core.serialization.property("featured_weight", core.serialization.number()),
        scopeProfiles: core.serialization.property("scope_profiles", core.serialization.list(AppScopeProfilesItem)),
    });

export declare namespace OauthApp {
    export interface Raw {
        id?: string | null;
        client_id: string;
        scopes?: string[] | null;
        additional_scopes?: string[] | null;
        redirect_uri?: string | null;
        owner_id: string;
        created_at?: string | null;
        updated_at?: string | null;
        name_slug: string;
        name: string;
        auth_type?: AppAuthType.Raw | null;
        description?: string | null;
        img_src: string;
        custom_fields_json?: string | null;
        categories: string[];
        featured_weight: number;
        scope_profiles: AppScopeProfilesItem.Raw[];
    }
}
