/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ObservationError } from "./ObservationError.js";

export const Observation: core.serialization.ObjectSchema<serializers.Observation.Raw, Pipedream.Observation> =
    core.serialization.object({
        err: ObservationError.optional(),
        k: core.serialization.string(),
        msg: core.serialization.string().optional(),
        ts: core.serialization.number(),
    });

export declare namespace Observation {
    export interface Raw {
        err?: ObservationError.Raw | null;
        k: string;
        msg?: string | null;
        ts: number;
    }
}
