/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ProjectInfoResponseAppsItem: core.serialization.ObjectSchema<
    serializers.ProjectInfoResponseAppsItem.Raw,
    Pipedream.ProjectInfoResponseAppsItem
> = core.serialization.object({
    id: core.serialization.string().optional(),
    nameSlug: core.serialization.property("name_slug", core.serialization.string()),
});

export declare namespace ProjectInfoResponseAppsItem {
    export interface Raw {
        id?: string | null;
        name_slug: string;
    }
}
