/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ProjectInfoResponse: core.serialization.ObjectSchema<
    serializers.ProjectInfoResponse.Raw,
    Pipedream.ProjectInfoResponse
> = core.serialization.object({
    apps: core.serialization.list(
        core.serialization.object({
            id: core.serialization.string().optional(),
            nameSlug: core.serialization.property("name_slug", core.serialization.string()),
        }),
    ),
});

export declare namespace ProjectInfoResponse {
    export interface Raw {
        apps: Array<{
            id?: string | null;
            name_slug: string;
        }>;
    }
}
