// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PropOptionValue } from "./PropOptionValue.js";

export const PropOption: core.serialization.ObjectSchema<serializers.PropOption.Raw, Pipedream.PropOption> =
    core.serialization.object({
        label: core.serialization.string(),
        value: PropOptionValue.nullable(),
    });

export declare namespace PropOption {
    export interface Raw {
        label: string;
        value?: PropOptionValue.Raw | null;
    }
}
