/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const PropOptionValue: core.serialization.Schema<serializers.PropOptionValue.Raw, Pipedream.PropOptionValue> =
    core.serialization.undiscriminatedUnion([core.serialization.string(), core.serialization.number()]);

export declare namespace PropOptionValue {
    export type Raw = string | number;
}
