// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { PropOption } from "./PropOption.js";

export const PropOptionNested: core.serialization.ObjectSchema<
    serializers.PropOptionNested.Raw,
    Pipedream.PropOptionNested
> = core.serialization.object({
    lv: core.serialization.property("__lv", PropOption),
});

export declare namespace PropOptionNested {
    export interface Raw {
        __lv: PropOption.Raw;
    }
}
