/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import { ConfigurableProp } from "./ConfigurableProp.js";

export const ReloadPropsResponse: core.serialization.ObjectSchema<
    serializers.ReloadPropsResponse.Raw,
    Pipedream.ReloadPropsResponse
> = core.serialization.object({
    configurableProps: core.serialization.property(
        "configurable_props",
        core.serialization.list(ConfigurableProp).optional(),
    ),
});

export declare namespace ReloadPropsResponse {
    export interface Raw {
        configurable_props?: ConfigurableProp.Raw[] | null;
    }
}
