// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { DynamicProps } from "./DynamicProps.js";
import { Observation } from "./Observation.js";

export const ReloadPropsResponse: core.serialization.ObjectSchema<
    serializers.ReloadPropsResponse.Raw,
    Pipedream.ReloadPropsResponse
> = core.serialization.object({
    observations: core.serialization.list(Observation).optional(),
    errors: core.serialization.list(core.serialization.string()).optional(),
    dynamicProps: DynamicProps.optional(),
});

export declare namespace ReloadPropsResponse {
    export interface Raw {
        observations?: Observation.Raw[] | null;
        errors?: string[] | null;
        dynamicProps?: DynamicProps.Raw | null;
    }
}
