// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { WebhookWithOptionalSigningKey } from "./WebhookWithOptionalSigningKey.js";

export const SetWebhookResponse: core.serialization.ObjectSchema<
    serializers.SetWebhookResponse.Raw,
    Pipedream.SetWebhookResponse
> = core.serialization.object({
    data: WebhookWithOptionalSigningKey,
});

export declare namespace SetWebhookResponse {
    export interface Raw {
        data: WebhookWithOptionalSigningKey.Raw;
    }
}
