/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const StartConnectOpts: core.serialization.ObjectSchema<
    serializers.StartConnectOpts.Raw,
    Pipedream.StartConnectOpts
> = core.serialization.object({
    iframe: core.serialization.string().optional(),
});

export declare namespace StartConnectOpts {
    export interface Raw {
        iframe?: string | null;
    }
}
