// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const StashId: core.serialization.Schema<serializers.StashId.Raw, Pipedream.StashId> = core.serialization
    .string()
    .optional();

export declare namespace StashId {
    export type Raw = string | null | undefined;
}
