/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const TimerInterval: core.serialization.ObjectSchema<serializers.TimerInterval.Raw, Pipedream.TimerInterval> =
    core.serialization.object({
        intervalSeconds: core.serialization.number(),
    });

export declare namespace TimerInterval {
    export interface Raw {
        intervalSeconds: number;
    }
}
