// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TimerInterface: core.serialization.ObjectSchema<serializers.TimerInterface.Raw, Pipedream.TimerInterface> =
    core.serialization.object({
        id: core.serialization.string(),
        intervalSeconds: core.serialization.property("interval_seconds", core.serialization.number().optional()),
        cron: core.serialization.string().optional(),
        timezone: core.serialization.string(),
        scheduleChangedAt: core.serialization.property("schedule_changed_at", core.serialization.number()),
        createdAt: core.serialization.property("created_at", core.serialization.number()),
        updatedAt: core.serialization.property("updated_at", core.serialization.number().optional()),
    });

export declare namespace TimerInterface {
    export interface Raw {
        id: string;
        interval_seconds?: number | null;
        cron?: string | null;
        timezone: string;
        schedule_changed_at: number;
        created_at: number;
        updated_at?: number | null;
    }
}
