/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const TimerCron: core.serialization.ObjectSchema<serializers.TimerCron.Raw, Pipedream.TimerCron> =
    core.serialization.object({
        cron: core.serialization.string(),
    });

export declare namespace TimerCron {
    export interface Raw {
        cron: string;
    }
}
