// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TooManyRequestsErrorBody: core.serialization.ObjectSchema<
    serializers.TooManyRequestsErrorBody.Raw,
    Pipedream.TooManyRequestsErrorBody
> = core.serialization.object({
    error: core.serialization.string().optional(),
});

export declare namespace TooManyRequestsErrorBody {
    export interface Raw {
        error?: string | null;
    }
}
