// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";

export const TriggerWebhookDeliveryBackend: core.serialization.Schema<
    serializers.TriggerWebhookDeliveryBackend.Raw,
    Pipedream.TriggerWebhookDeliveryBackend
> = core.serialization.enum_(["jvm", "valkey"]);

export declare namespace TriggerWebhookDeliveryBackend {
    export type Raw = "jvm" | "valkey";
}
