// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";
import type * as serializers from "../index.js";
import { App } from "./App.js";

export const ValidateTokenResponse: core.serialization.ObjectSchema<
    serializers.ValidateTokenResponse.Raw,
    Pipedream.ValidateTokenResponse
> = core.serialization.object({
    app: App.optional(),
    error: core.serialization.string().optional(),
    errorRedirectUri: core.serialization.property("error_redirect_uri", core.serialization.string().optional()),
    oauthAppId: core.serialization.property("oauth_app_id", core.serialization.string().optional()),
    projectAppName: core.serialization.property("project_app_name", core.serialization.string().optional()),
    projectEnvironment: core.serialization.property("project_environment", core.serialization.string().optional()),
    projectId: core.serialization.property("project_id", core.serialization.string().optional()),
    projectSupportEmail: core.serialization.property("project_support_email", core.serialization.string().optional()),
    success: core.serialization.boolean(),
    successRedirectUri: core.serialization.property("success_redirect_uri", core.serialization.string().optional()),
});

export declare namespace ValidateTokenResponse {
    export interface Raw {
        app?: App.Raw | null;
        error?: string | null;
        error_redirect_uri?: string | null;
        oauth_app_id?: string | null;
        project_app_name?: string | null;
        project_environment?: string | null;
        project_id?: string | null;
        project_support_email?: string | null;
        success: boolean;
        success_redirect_uri?: string | null;
    }
}
