/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../index.js";
import * as Pipedream from "../../api/index.js";
import * as core from "../../core/index.js";

export const ValidateTokenParams: core.serialization.ObjectSchema<
    serializers.ValidateTokenParams.Raw,
    Pipedream.ValidateTokenParams
> = core.serialization.object({
    appId: core.serialization.property("app_id", core.serialization.string()),
    oauthAppId: core.serialization.property("oauth_app_id", core.serialization.string().optional()),
});

export declare namespace ValidateTokenParams {
    export interface Raw {
        app_id: string;
        oauth_app_id?: string | null;
    }
}
