// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const ListComponentsRequestRegistry: core.serialization.Schema<
    serializers.ListComponentsRequestRegistry.Raw,
    Pipedream.ListComponentsRequestRegistry
> = core.serialization.enum_(["public", "private", "all"]);

export declare namespace ListComponentsRequestRegistry {
    export type Raw = "public" | "private" | "all";
}
