// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version: "1.2.3"
 *     }
 */
export interface ComponentsRetrieveRequest {
    /** Optional semantic version of the component to retrieve (for example '1.0.0') */
    version?: string;
}
