// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         version: "1.0.0"
 *     }
 */
export interface ComponentsRetrieveRequest {
    /** Optional semantic version of the component to retrieve */
    version?: string;
}
