// This file was auto-generated by Fern from our API Definition.

import type * as Pipedream from "../../../../api/index.js";
import * as core from "../../../../core/index.js";
import type * as serializers from "../../../index.js";

export const AppsListRequestSortKey: core.serialization.Schema<
    serializers.AppsListRequestSortKey.Raw,
    Pipedream.AppsListRequestSortKey
> = core.serialization.enum_(["name", "name_slug", "featured_weight"]);

export declare namespace AppsListRequestSortKey {
    export type Raw = "name" | "name_slug" | "featured_weight";
}
