// This file was auto-generated by Fern from our API Definition.

import { PipedreamClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("AppCategoriesClient", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "projectId",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = [{ id: "id", name: "name", description: "description" }];
        server
            .mockEndpoint()
            .get("/v1/connect/app_categories")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.appCategories.list();
        expect(response).toEqual([
            {
                id: "id",
                name: "name",
                description: "description",
            },
        ]);
    });

    test("retrieve", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "projectId",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { id: "id", name: "name", description: "description" };
        server
            .mockEndpoint()
            .get("/v1/connect/app_categories/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.appCategories.retrieve("id");
        expect(response).toEqual({
            id: "id",
            name: "name",
            description: "description",
        });
    });
});
