// This file was auto-generated by Fern from our API Definition.

import type { MockServer } from "../mock-server/MockServer";

export function mockOAuth(server: MockServer): void {
    const rawRequestBody = { grant_type: "client_credentials", client_id: "client_id", client_secret: "client_secret" };
    const rawResponseBody = { access_token: "access_token", token_type: "token_type", expires_in: 1 };
    server
        .mockEndpoint()
        .post("/v1/oauth/token")
        .jsonBody(rawRequestBody)
        .respondWith()
        .statusCode(200)
        .jsonBody(rawResponseBody)
        .build();
}
