// This file was auto-generated by Fern from our API Definition.

import * as Pipedream from "../../src/api/index";
import { PipedreamClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("OauthAppsClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    id: "id",
                    name_slug: "name_slug",
                    name: "name",
                    auth_type: "keys",
                    description: "description",
                    img_src: "img_src",
                    custom_fields_json: "custom_fields_json",
                    categories: ["categories"],
                    featured_weight: 1.1,
                    scope_profiles: [{ name: "read_only", scopes: ["scopes"] }],
                    client_id: "client_id",
                    scopes: ["scopes"],
                    additional_scopes: ["additional_scopes"],
                    redirect_uri: "redirect_uri",
                    owner_id: "owner_id",
                    created_at: "2024-01-15T09:30:00Z",
                    updated_at: "2024-01-15T09:30:00Z",
                },
            ],
            page_info: { count: 10, total_count: 120, start_cursor: "start_cursor", end_cursor: "end_cursor" },
        };

        server
            .mockEndpoint({ once: false })
            .get("/v1/connect/project_id/oauth_apps")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    id: "id",
                    nameSlug: "name_slug",
                    name: "name",
                    authType: "keys",
                    description: "description",
                    imgSrc: "img_src",
                    customFieldsJson: "custom_fields_json",
                    categories: ["categories"],
                    featuredWeight: 1.1,
                    scopeProfiles: [
                        {
                            name: "read_only",
                            scopes: ["scopes"],
                        },
                    ],
                    clientId: "client_id",
                    scopes: ["scopes"],
                    additionalScopes: ["additional_scopes"],
                    redirectUri: "redirect_uri",
                    ownerId: "owner_id",
                    createdAt: new Date("2024-01-15T09:30:00.000Z"),
                    updatedAt: new Date("2024-01-15T09:30:00.000Z"),
                },
            ],
            pageInfo: {
                count: 10,
                totalCount: 120,
                startCursor: "start_cursor",
                endCursor: "end_cursor",
            },
        };
        const page = await client.oauthApps.list({
            after: "after",
            before: "before",
            limit: 1,
            app: "app",
            q: "q",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/connect/project_id/oauth_apps")
            .respondWith()
            .statusCode(404)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.list();
        }).rejects.toThrow(Pipedream.NotFoundError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/connect/project_id/oauth_apps")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.list();
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { app: "app", client_id: "client_id", client_secret: "client_secret" };
        const rawResponseBody = {
            id: "id",
            name_slug: "name_slug",
            name: "name",
            auth_type: "keys",
            description: "description",
            img_src: "img_src",
            custom_fields_json: "custom_fields_json",
            categories: ["categories"],
            featured_weight: 1.1,
            scope_profiles: [{ name: "read_only", scopes: ["scopes"] }],
            client_id: "client_id",
            scopes: ["scopes"],
            additional_scopes: ["additional_scopes"],
            redirect_uri: "redirect_uri",
            owner_id: "owner_id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .post("/v1/connect/project_id/oauth_apps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.oauthApps.create({
            app: "app",
            clientId: "client_id",
            clientSecret: "client_secret",
        });
        expect(response).toEqual({
            id: "id",
            nameSlug: "name_slug",
            name: "name",
            authType: "keys",
            description: "description",
            imgSrc: "img_src",
            customFieldsJson: "custom_fields_json",
            categories: ["categories"],
            featuredWeight: 1.1,
            scopeProfiles: [
                {
                    name: "read_only",
                    scopes: ["scopes"],
                },
            ],
            clientId: "client_id",
            scopes: ["scopes"],
            additionalScopes: ["additional_scopes"],
            redirectUri: "redirect_uri",
            ownerId: "owner_id",
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { app: "app", client_id: "client_id", client_secret: "client_secret" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/connect/project_id/oauth_apps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.create({
                app: "app",
                clientId: "client_id",
                clientSecret: "client_secret",
            });
        }).rejects.toThrow(Pipedream.BadRequestError);
    });

    test("create (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { app: "app", client_id: "client_id", client_secret: "client_secret" };
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .post("/v1/connect/project_id/oauth_apps")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.create({
                app: "app",
                clientId: "client_id",
                clientSecret: "client_secret",
            });
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            id: "id",
            name_slug: "name_slug",
            name: "name",
            auth_type: "keys",
            description: "description",
            img_src: "img_src",
            custom_fields_json: "custom_fields_json",
            categories: ["categories"],
            featured_weight: 1.1,
            scope_profiles: [{ name: "read_only", scopes: ["scopes"] }],
            client_id: "client_id",
            scopes: ["scopes"],
            additional_scopes: ["additional_scopes"],
            redirect_uri: "redirect_uri",
            owner_id: "owner_id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .get("/v1/connect/project_id/oauth_apps/id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.oauthApps.retrieve("id");
        expect(response).toEqual({
            id: "id",
            nameSlug: "name_slug",
            name: "name",
            authType: "keys",
            description: "description",
            imgSrc: "img_src",
            customFieldsJson: "custom_fields_json",
            categories: ["categories"],
            featuredWeight: 1.1,
            scopeProfiles: [
                {
                    name: "read_only",
                    scopes: ["scopes"],
                },
            ],
            clientId: "client_id",
            scopes: ["scopes"],
            additionalScopes: ["additional_scopes"],
            redirectUri: "redirect_uri",
            ownerId: "owner_id",
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .get("/v1/connect/project_id/oauth_apps/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.retrieve("id");
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("update (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = {
            id: "id",
            name_slug: "name_slug",
            name: "name",
            auth_type: "keys",
            description: "description",
            img_src: "img_src",
            custom_fields_json: "custom_fields_json",
            categories: ["categories"],
            featured_weight: 1.1,
            scope_profiles: [{ name: "read_only", scopes: ["scopes"] }],
            client_id: "client_id",
            scopes: ["scopes"],
            additional_scopes: ["additional_scopes"],
            redirect_uri: "redirect_uri",
            owner_id: "owner_id",
            created_at: "2024-01-15T09:30:00Z",
            updated_at: "2024-01-15T09:30:00Z",
        };

        server
            .mockEndpoint()
            .put("/v1/connect/project_id/oauth_apps/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.oauthApps.update("id");
        expect(response).toEqual({
            id: "id",
            nameSlug: "name_slug",
            name: "name",
            authType: "keys",
            description: "description",
            imgSrc: "img_src",
            customFieldsJson: "custom_fields_json",
            categories: ["categories"],
            featuredWeight: 1.1,
            scopeProfiles: [
                {
                    name: "read_only",
                    scopes: ["scopes"],
                },
            ],
            clientId: "client_id",
            scopes: ["scopes"],
            additionalScopes: ["additional_scopes"],
            redirectUri: "redirect_uri",
            ownerId: "owner_id",
            createdAt: new Date("2024-01-15T09:30:00.000Z"),
            updatedAt: new Date("2024-01-15T09:30:00.000Z"),
        });
    });

    test("update (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = {};
        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .put("/v1/connect/project_id/oauth_apps/id")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.update("id");
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("delete (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        server.mockEndpoint().delete("/v1/connect/project_id/oauth_apps/id").respondWith().statusCode(200).build();

        const response = await client.oauthApps.delete("id");
        expect(response).toEqual(undefined);
    });

    test("delete (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/connect/project_id/oauth_apps/id")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.delete("id");
        }).rejects.toThrow(Pipedream.BadRequestError);
    });

    test("delete (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };

        server
            .mockEndpoint()
            .delete("/v1/connect/project_id/oauth_apps/id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.oauthApps.delete("id");
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });
});
