// This file was auto-generated by Fern from our API Definition.

import * as Pipedream from "../../src/api/index";
import { PipedreamClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("TokensClient", () => {
    test("create (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { external_user_id: "external_user_id" };
        const rawResponseBody = {
            connect_link_url: "connect_link_url",
            expires_at: "2024-01-15T09:30:00Z",
            token: "token",
        };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tokens.create({
            projectId: "project_id",
            externalUserId: "external_user_id",
        });
        expect(response).toEqual({
            connectLinkUrl: "connect_link_url",
            expiresAt: new Date("2024-01-15T09:30:00.000Z"),
            token: "token",
        });
    });

    test("create (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { external_user_id: "external_user_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/tokens")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tokens.create({
                projectId: "project_id",
                externalUserId: "external_user_id",
            });
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("validate (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "projectId",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            app: {
                id: "id",
                name_slug: "name_slug",
                name: "name",
                auth_type: "keys",
                description: "description",
                img_src: "img_src",
                custom_fields_json: "custom_fields_json",
                categories: ["categories"],
                featured_weight: 1.1,
            },
            error: "error",
            error_redirect_uri: "error_redirect_uri",
            oauth_app_id: "oauth_app_id",
            project_app_name: "project_app_name",
            project_environment: "project_environment",
            project_id: "project_id",
            project_support_email: "project_support_email",
            success: true,
            success_redirect_uri: "success_redirect_uri",
        };
        server
            .mockEndpoint()
            .get("/v1/connect/tokens/ctok/validate")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.tokens.validate({
            ctok: "ctok",
            appId: "app_id",
        });
        expect(response).toEqual({
            app: {
                id: "id",
                nameSlug: "name_slug",
                name: "name",
                authType: "keys",
                description: "description",
                imgSrc: "img_src",
                customFieldsJson: "custom_fields_json",
                categories: ["categories"],
                featuredWeight: 1.1,
            },
            error: "error",
            errorRedirectUri: "error_redirect_uri",
            oauthAppId: "oauth_app_id",
            projectAppName: "project_app_name",
            projectEnvironment: "project_environment",
            projectId: "project_id",
            projectSupportEmail: "project_support_email",
            success: true,
            successRedirectUri: "success_redirect_uri",
        });
    });

    test("validate (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "projectId",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/connect/tokens/ctok/validate")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.tokens.validate({
                ctok: "ctok",
                appId: "app_id",
            });
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });
});
