// This file was auto-generated by Fern from our API Definition.

import * as Pipedream from "../../src/api/index";
import { PipedreamClient } from "../../src/Client";
import { mockServerPool } from "../mock-server/MockServerPool";
import { mockOAuth } from "./mockAuth";

describe("TriggersClient", () => {
    test("list (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: [
                {
                    key: "key",
                    name: "name",
                    version: "version",
                    configurable_props: [{ type: "alert", name: "name", content: "content" }],
                    description: "description",
                    component_type: "component_type",
                    stash: "optional",
                },
            ],
            page_info: { count: 1, total_count: 1, start_cursor: "start_cursor", end_cursor: "end_cursor" },
        };
        server
            .mockEndpoint({ once: false })
            .get("/v1/connect/project_id/triggers")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const expected = {
            data: [
                {
                    key: "key",
                    name: "name",
                    version: "version",
                    configurableProps: [
                        {
                            type: "alert",
                            name: "name",
                            content: "content",
                        },
                    ],
                    description: "description",
                    componentType: "component_type",
                    stash: "optional",
                },
            ],
            pageInfo: {
                count: 1,
                totalCount: 1,
                startCursor: "start_cursor",
                endCursor: "end_cursor",
            },
        };
        const page = await client.triggers.list({
            after: "after",
            before: "before",
            limit: 1,
            q: "q",
            app: "app",
            registry: "public",
        });

        expect(expected.data).toEqual(page.data);
        expect(page.hasNextPage()).toBe(true);
        const nextPage = await page.getNextPage();
        expect(expected.data).toEqual(nextPage.data);
    });

    test("list (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/connect/project_id/triggers")
            .respondWith()
            .statusCode(400)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.triggers.list();
        }).rejects.toThrow(Pipedream.BadRequestError);
    });

    test("list (3)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/connect/project_id/triggers")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.triggers.list();
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("retrieve (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = {
            data: {
                key: "key",
                name: "name",
                version: "version",
                configurable_props: [{ type: "alert", name: "name", content: "content" }],
                description: "description",
                component_type: "component_type",
                stash: "optional",
                annotations: {
                    destructiveHint: true,
                    idempotentHint: true,
                    openWorldHint: true,
                    readOnlyHint: true,
                    title: "title",
                },
            },
        };
        server
            .mockEndpoint()
            .get("/v1/connect/project_id/triggers/component_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.triggers.retrieve("component_id", {
            version: "1.2.3",
        });
        expect(response).toEqual({
            data: {
                key: "key",
                name: "name",
                version: "version",
                configurableProps: [
                    {
                        type: "alert",
                        name: "name",
                        content: "content",
                    },
                ],
                description: "description",
                componentType: "component_type",
                stash: "optional",
                annotations: {
                    destructiveHint: true,
                    idempotentHint: true,
                    openWorldHint: true,
                    readOnlyHint: true,
                    title: "title",
                },
            },
        });
    });

    test("retrieve (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });

        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .get("/v1/connect/project_id/triggers/component_id")
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.triggers.retrieve("component_id");
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("configureProp (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { id: "id", external_user_id: "external_user_id", prop_name: "prop_name" };
        const rawResponseBody = {
            options: [{ label: "label", value: "value" }],
            stringOptions: ["stringOptions"],
            observations: [{ k: "k", msg: "msg", ts: 1.1 }],
            context: { key: "value" },
            errors: ["errors"],
        };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/triggers/configure")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.triggers.configureProp({
            id: "id",
            externalUserId: "external_user_id",
            propName: "prop_name",
        });
        expect(response).toEqual({
            options: [
                {
                    label: "label",
                    value: "value",
                },
            ],
            stringOptions: ["stringOptions"],
            observations: [
                {
                    k: "k",
                    msg: "msg",
                    ts: 1.1,
                },
            ],
            context: {
                key: "value",
            },
            errors: ["errors"],
        });
    });

    test("configureProp (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { id: "id", external_user_id: "external_user_id", prop_name: "prop_name" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/triggers/configure")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.triggers.configureProp({
                id: "id",
                externalUserId: "external_user_id",
                propName: "prop_name",
            });
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("reloadProps (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { id: "id", external_user_id: "external_user_id" };
        const rawResponseBody = {
            observations: [{ k: "k", msg: "msg", ts: 1.1 }],
            errors: ["errors"],
            dynamicProps: { id: "id", configurableProps: [{ type: "alert", name: "name", content: "content" }] },
        };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/triggers/props")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.triggers.reloadProps({
            id: "id",
            externalUserId: "external_user_id",
        });
        expect(response).toEqual({
            observations: [
                {
                    k: "k",
                    msg: "msg",
                    ts: 1.1,
                },
            ],
            errors: ["errors"],
            dynamicProps: {
                id: "id",
                configurableProps: [
                    {
                        type: "alert",
                        name: "name",
                        content: "content",
                    },
                ],
            },
        });
    });

    test("reloadProps (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { id: "id", external_user_id: "external_user_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/triggers/props")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.triggers.reloadProps({
                id: "id",
                externalUserId: "external_user_id",
            });
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });

    test("deploy (1)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { id: "id", external_user_id: "external_user_id" };
        const rawResponseBody = {
            data: {
                type: "DeployedComponent",
                id: "id",
                owner_id: "owner_id",
                component_id: "component_id",
                component_key: "component_key",
                configurable_props: [{ type: "alert", name: "name", content: "content" }],
                configured_props: { key: { key: "value" } },
                active: true,
                created_at: 1,
                updated_at: 1,
                name: "name",
                name_slug: "name_slug",
                callback_observations: { key: "value" },
                emit_on_deploy: true,
            },
        };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/triggers/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.triggers.deploy({
            id: "id",
            externalUserId: "external_user_id",
        });
        expect(response).toEqual({
            data: {
                type: "DeployedComponent",
                id: "id",
                ownerId: "owner_id",
                componentId: "component_id",
                componentKey: "component_key",
                configurableProps: [
                    {
                        type: "alert",
                        name: "name",
                        content: "content",
                    },
                ],
                configuredProps: {
                    key: {
                        key: "value",
                    },
                },
                active: true,
                createdAt: 1,
                updatedAt: 1,
                name: "name",
                nameSlug: "name_slug",
                callbackObservations: {
                    key: "value",
                },
                emitOnDeploy: true,
            },
        });
    });

    test("deploy (2)", async () => {
        const server = mockServerPool.createServer();
        mockOAuth(server);

        const client = new PipedreamClient({
            maxRetries: 0,
            projectId: "project_id",
            clientId: "client_id",
            clientSecret: "client_secret",
            projectEnvironment: "test",
            environment: server.baseUrl,
        });
        const rawRequestBody = { id: "id", external_user_id: "external_user_id" };
        const rawResponseBody = { key: "value" };
        server
            .mockEndpoint()
            .post("/v1/connect/project_id/triggers/deploy")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(429)
            .jsonBody(rawResponseBody)
            .build();

        await expect(async () => {
            return await client.triggers.deploy({
                id: "id",
                externalUserId: "external_user_id",
            });
        }).rejects.toThrow(Pipedream.TooManyRequestsError);
    });
});
