// This file was auto-generated by Fern from our API Definition.

import { AccountsClient } from "./api/resources/accounts/client/Client.js";
import { ActionsClient } from "./api/resources/actions/client/Client.js";
import { AppCategoriesClient } from "./api/resources/appCategories/client/Client.js";
import { AppsClient } from "./api/resources/apps/client/Client.js";
import { ComponentsClient } from "./api/resources/components/client/Client.js";
import { DeployedTriggersClient } from "./api/resources/deployedTriggers/client/Client.js";
import { FileStashClient } from "./api/resources/fileStash/client/Client.js";
import { OauthTokensClient } from "./api/resources/oauthTokens/client/Client.js";
import { ProjectsClient } from "./api/resources/projects/client/Client.js";
import { ProxyClient } from "./api/resources/proxy/client/Client.js";
import { TokensClient } from "./api/resources/tokens/client/Client.js";
import { TriggersClient } from "./api/resources/triggers/client/Client.js";
import { UsersClient } from "./api/resources/users/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";

export declare namespace PipedreamClient {
    export type Options = BaseClientOptions;

    export interface RequestOptions extends BaseRequestOptions {}
}

export class PipedreamClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<PipedreamClient.Options>;
    protected _appCategories: AppCategoriesClient | undefined;
    protected _apps: AppsClient | undefined;
    protected _accounts: AccountsClient | undefined;
    protected _users: UsersClient | undefined;
    protected _components: ComponentsClient | undefined;
    protected _actions: ActionsClient | undefined;
    protected _triggers: TriggersClient | undefined;
    protected _deployedTriggers: DeployedTriggersClient | undefined;
    protected _projects: ProjectsClient | undefined;
    protected _fileStash: FileStashClient | undefined;
    protected _proxy: ProxyClient | undefined;
    protected _tokens: TokensClient | undefined;
    protected _oauthTokens: OauthTokensClient | undefined;

    constructor(options: PipedreamClient.Options) {
        this._options = normalizeClientOptionsWithAuth(options);
    }

    public get appCategories(): AppCategoriesClient {
        return (this._appCategories ??= new AppCategoriesClient(this._options));
    }

    public get apps(): AppsClient {
        return (this._apps ??= new AppsClient(this._options));
    }

    public get accounts(): AccountsClient {
        return (this._accounts ??= new AccountsClient(this._options));
    }

    public get users(): UsersClient {
        return (this._users ??= new UsersClient(this._options));
    }

    public get components(): ComponentsClient {
        return (this._components ??= new ComponentsClient(this._options));
    }

    public get actions(): ActionsClient {
        return (this._actions ??= new ActionsClient(this._options));
    }

    public get triggers(): TriggersClient {
        return (this._triggers ??= new TriggersClient(this._options));
    }

    public get deployedTriggers(): DeployedTriggersClient {
        return (this._deployedTriggers ??= new DeployedTriggersClient(this._options));
    }

    public get projects(): ProjectsClient {
        return (this._projects ??= new ProjectsClient(this._options));
    }

    public get fileStash(): FileStashClient {
        return (this._fileStash ??= new FileStashClient(this._options));
    }

    public get proxy(): ProxyClient {
        return (this._proxy ??= new ProxyClient(this._options));
    }

    public get tokens(): TokensClient {
        return (this._tokens ??= new TokensClient(this._options));
    }

    public get oauthTokens(): OauthTokensClient {
        return (this._oauthTokens ??= new OauthTokensClient(this._options));
    }
}
