/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Pipedream from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as serializers from "../../../../serialization/index.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Proxy {
    export interface Options {
        environment?: core.Supplier<environments.PipedreamEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        projectId: string;
        token?: core.Supplier<core.BearerToken | undefined>;
        /** Override the x-pd-environment header */
        projectEnvironment?: core.Supplier<Pipedream.ProjectEnvironment | undefined>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Override the x-pd-environment header */
        projectEnvironment?: Pipedream.ProjectEnvironment | undefined;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | null | undefined> | null | undefined>;
    }
}

export class Proxy {
    protected readonly _options: Proxy.Options;

    constructor(_options: Proxy.Options) {
        this._options = _options;
    }

    /**
     * Forward an authenticated GET request to an external API using an external user's account credentials
     *
     * @param {string} url64 - Base64-encoded target URL
     * @param {Pipedream.ProxyGetRequest} request
     * @param {Proxy.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pipedream.TooManyRequestsError}
     *
     * @example
     *     await client.proxy.get("url_64", {
     *         externalUserId: "external_user_id",
     *         accountId: "account_id"
     *     })
     */
    public get(
        url64: string,
        request: Pipedream.ProxyGetRequest,
        requestOptions?: Proxy.RequestOptions,
    ): core.HttpResponsePromise<Pipedream.ProxyResponse | undefined> {
        return core.HttpResponsePromise.fromPromise(this.__get(url64, request, requestOptions));
    }

    private async __get(
        url64: string,
        request: Pipedream.ProxyGetRequest,
        requestOptions?: Proxy.RequestOptions,
    ): Promise<core.WithRawResponse<Pipedream.ProxyResponse | undefined>> {
        const { externalUserId, accountId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["external_user_id"] = externalUserId;
        _queryParams["account_id"] = accountId;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-pd-environment": requestOptions?.projectEnvironment ?? this._options?.projectEnvironment,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PipedreamEnvironment.Prod,
                `v1/connect/${encodeURIComponent(this._options.projectId)}/proxy/${encodeURIComponent(url64)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ProxyResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 429:
                    throw new Pipedream.TooManyRequestsError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.PipedreamError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PipedreamError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PipedreamTimeoutError(
                    "Timeout exceeded when calling GET /v1/connect/{project_id}/proxy/{url_64}.",
                );
            case "unknown":
                throw new errors.PipedreamError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Forward an authenticated POST request to an external API using an external user's account credentials
     *
     * @param {string} url64 - Base64-encoded target URL
     * @param {Pipedream.ProxyPostRequest} request
     * @param {Proxy.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pipedream.TooManyRequestsError}
     *
     * @example
     *     await client.proxy.post("url_64", {
     *         externalUserId: "external_user_id",
     *         accountId: "account_id",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public post(
        url64: string,
        request: Pipedream.ProxyPostRequest,
        requestOptions?: Proxy.RequestOptions,
    ): core.HttpResponsePromise<Pipedream.ProxyResponse | undefined> {
        return core.HttpResponsePromise.fromPromise(this.__post(url64, request, requestOptions));
    }

    private async __post(
        url64: string,
        request: Pipedream.ProxyPostRequest,
        requestOptions?: Proxy.RequestOptions,
    ): Promise<core.WithRawResponse<Pipedream.ProxyResponse | undefined>> {
        const { externalUserId, accountId, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["external_user_id"] = externalUserId;
        _queryParams["account_id"] = accountId;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-pd-environment": requestOptions?.projectEnvironment ?? this._options?.projectEnvironment,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PipedreamEnvironment.Prod,
                `v1/connect/${encodeURIComponent(this._options.projectId)}/proxy/${encodeURIComponent(url64)}`,
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.proxy.post.Request.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ProxyResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 429:
                    throw new Pipedream.TooManyRequestsError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.PipedreamError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PipedreamError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PipedreamTimeoutError(
                    "Timeout exceeded when calling POST /v1/connect/{project_id}/proxy/{url_64}.",
                );
            case "unknown":
                throw new errors.PipedreamError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Forward an authenticated PUT request to an external API using an external user's account credentials
     *
     * @param {string} url64 - Base64-encoded target URL
     * @param {Pipedream.ProxyPutRequest} request
     * @param {Proxy.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pipedream.TooManyRequestsError}
     *
     * @example
     *     await client.proxy.put("url_64", {
     *         externalUserId: "external_user_id",
     *         accountId: "account_id",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public put(
        url64: string,
        request: Pipedream.ProxyPutRequest,
        requestOptions?: Proxy.RequestOptions,
    ): core.HttpResponsePromise<Pipedream.ProxyResponse | undefined> {
        return core.HttpResponsePromise.fromPromise(this.__put(url64, request, requestOptions));
    }

    private async __put(
        url64: string,
        request: Pipedream.ProxyPutRequest,
        requestOptions?: Proxy.RequestOptions,
    ): Promise<core.WithRawResponse<Pipedream.ProxyResponse | undefined>> {
        const { externalUserId, accountId, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["external_user_id"] = externalUserId;
        _queryParams["account_id"] = accountId;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-pd-environment": requestOptions?.projectEnvironment ?? this._options?.projectEnvironment,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PipedreamEnvironment.Prod,
                `v1/connect/${encodeURIComponent(this._options.projectId)}/proxy/${encodeURIComponent(url64)}`,
            ),
            method: "PUT",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.proxy.put.Request.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ProxyResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 429:
                    throw new Pipedream.TooManyRequestsError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.PipedreamError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PipedreamError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PipedreamTimeoutError(
                    "Timeout exceeded when calling PUT /v1/connect/{project_id}/proxy/{url_64}.",
                );
            case "unknown":
                throw new errors.PipedreamError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Forward an authenticated DELETE request to an external API using an external user's account credentials
     *
     * @param {string} url64 - Base64-encoded target URL
     * @param {Pipedream.ProxyDeleteRequest} request
     * @param {Proxy.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pipedream.TooManyRequestsError}
     *
     * @example
     *     await client.proxy.delete("url_64", {
     *         externalUserId: "external_user_id",
     *         accountId: "account_id"
     *     })
     */
    public delete(
        url64: string,
        request: Pipedream.ProxyDeleteRequest,
        requestOptions?: Proxy.RequestOptions,
    ): core.HttpResponsePromise<Pipedream.ProxyResponse | undefined> {
        return core.HttpResponsePromise.fromPromise(this.__delete(url64, request, requestOptions));
    }

    private async __delete(
        url64: string,
        request: Pipedream.ProxyDeleteRequest,
        requestOptions?: Proxy.RequestOptions,
    ): Promise<core.WithRawResponse<Pipedream.ProxyResponse | undefined>> {
        const { externalUserId, accountId } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["external_user_id"] = externalUserId;
        _queryParams["account_id"] = accountId;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-pd-environment": requestOptions?.projectEnvironment ?? this._options?.projectEnvironment,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PipedreamEnvironment.Prod,
                `v1/connect/${encodeURIComponent(this._options.projectId)}/proxy/${encodeURIComponent(url64)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ProxyResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 429:
                    throw new Pipedream.TooManyRequestsError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.PipedreamError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PipedreamError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PipedreamTimeoutError(
                    "Timeout exceeded when calling DELETE /v1/connect/{project_id}/proxy/{url_64}.",
                );
            case "unknown":
                throw new errors.PipedreamError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Forward an authenticated PATCH request to an external API using an external user's account credentials
     *
     * @param {string} url64 - Base64-encoded target URL
     * @param {Pipedream.ProxyPatchRequest} request
     * @param {Proxy.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @throws {@link Pipedream.TooManyRequestsError}
     *
     * @example
     *     await client.proxy.patch("url_64", {
     *         externalUserId: "external_user_id",
     *         accountId: "account_id",
     *         body: {
     *             "key": "value"
     *         }
     *     })
     */
    public patch(
        url64: string,
        request: Pipedream.ProxyPatchRequest,
        requestOptions?: Proxy.RequestOptions,
    ): core.HttpResponsePromise<Pipedream.ProxyResponse | undefined> {
        return core.HttpResponsePromise.fromPromise(this.__patch(url64, request, requestOptions));
    }

    private async __patch(
        url64: string,
        request: Pipedream.ProxyPatchRequest,
        requestOptions?: Proxy.RequestOptions,
    ): Promise<core.WithRawResponse<Pipedream.ProxyResponse | undefined>> {
        const { externalUserId, accountId, body: _body } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        _queryParams["external_user_id"] = externalUserId;
        _queryParams["account_id"] = accountId;
        let _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({
                Authorization: await this._getAuthorizationHeader(),
                "x-pd-environment": requestOptions?.projectEnvironment ?? this._options?.projectEnvironment,
            }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.PipedreamEnvironment.Prod,
                `v1/connect/${encodeURIComponent(this._options.projectId)}/proxy/${encodeURIComponent(url64)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            requestType: "json",
            body: serializers.proxy.patch.Request.jsonOrThrow(_body, {
                unrecognizedObjectKeys: "strip",
                omitUndefined: true,
            }),
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: serializers.ProxyResponse.parseOrThrow(_response.body, {
                    unrecognizedObjectKeys: "passthrough",
                    allowUnrecognizedUnionMembers: true,
                    allowUnrecognizedEnumValues: true,
                    skipValidation: true,
                    breadcrumbsPrefix: ["response"],
                }),
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            switch (_response.error.statusCode) {
                case 429:
                    throw new Pipedream.TooManyRequestsError(_response.error.body, _response.rawResponse);
                default:
                    throw new errors.PipedreamError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
            }
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.PipedreamError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.PipedreamTimeoutError(
                    "Timeout exceeded when calling PATCH /v1/connect/{project_id}/proxy/{url_64}.",
                );
            case "unknown":
                throw new errors.PipedreamError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        const bearer = await core.Supplier.get(this._options.token);
        if (bearer != null) {
            return `Bearer ${bearer}`;
        }

        return undefined;
    }
}
