// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         externalUserId: "external_user_id"
 *     }
 */
export interface CreateTokenOpts {
    /** The project ID, which starts with `proj_`. */
    projectId: string;
    /** List of allowed origins for CORS */
    allowedOrigins?: string[];
    /** URI to redirect to on error */
    errorRedirectUri?: string;
    /** Your end user ID, for whom you're creating the token */
    externalUserId: string;
    /** URI to redirect to on success */
    successRedirectUri?: string;
    /** Webhook URI for notifications */
    webhookUri?: string;
}
