// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         projectId: "project_id",
 *         url64: "url_64",
 *         externalUserId: "external_user_id",
 *         accountId: "account_id",
 *         body: {
 *             "string": {
 *                 "key": "value"
 *             }
 *         }
 *     }
 */
export interface PatchProxyRequest {
    /** The project ID, which starts with 'proj_'. */
    projectId: string;
    /** Base64-encoded target URL */
    url64: string;
    /** The external user ID for the proxy request */
    externalUserId: string;
    /** The account ID to use for authentication */
    accountId: string;
    /** Request body to forward to the target API */
    body: Record<string, unknown>;
}
