/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         externalUserId: "external_user_id",
 *         accountId: "account_id"
 *     }
 */
export interface ProxyGetRequest {
    /** The external user ID for the proxy request */
    externalUserId: string;
    /** The account ID to use for authentication */
    accountId: string;
}
