// This file was auto-generated by Fern from our API Definition.

import { OauthTokensClient } from "../api/resources/oauthTokens/client/Client.js";
import type { BaseClientOptions } from "../BaseClient.js";
import * as core from "../core/index.js";
import * as errors from "../errors/index.js";

export class OAuthAuthProvider implements core.AuthProvider {
    private readonly BUFFER_IN_MINUTES: number = 2;
    private readonly _clientId: core.Supplier<string> | undefined;
    private readonly _clientSecret: core.Supplier<string> | undefined;
    private readonly _authClient: OauthTokensClient;
    private _accessToken: string | undefined;
    private _expiresAt: Date;
    private _refreshPromise: Promise<string> | undefined;

    constructor(options: OAuthAuthProvider.Options) {
        this._clientId = options.clientId;
        this._clientSecret = options.clientSecret;
        this._authClient = new OauthTokensClient(options);
        this._expiresAt = new Date();
    }

    public static canCreate(options: OAuthAuthProvider.Options): boolean {
        return (
            (options.clientId != null || process.env?.PIPEDREAM_CLIENT_ID != null) &&
            (options.clientSecret != null || process.env?.PIPEDREAM_CLIENT_SECRET != null)
        );
    }

    public async getAuthRequest(arg?: { endpointMetadata?: core.EndpointMetadata }): Promise<core.AuthRequest> {
        const token = await this.getToken(arg);

        return {
            headers: {
                Authorization: `Bearer ${token}`,
            },
        };
    }

    private async getToken(arg?: { endpointMetadata?: core.EndpointMetadata }): Promise<string> {
        if (this._accessToken && this._expiresAt > new Date()) {
            return this._accessToken;
        }
        // If a refresh is already in progress, return the existing promise
        if (this._refreshPromise != null) {
            return this._refreshPromise;
        }
        return this.refresh(arg);
    }

    private async refresh(_arg?: { endpointMetadata?: core.EndpointMetadata }): Promise<string> {
        this._refreshPromise = (async () => {
            try {
                const clientId = (await core.Supplier.get(this._clientId)) ?? process.env?.PIPEDREAM_CLIENT_ID;
                if (clientId == null) {
                    throw new errors.PipedreamError({
                        message:
                            "clientId is required; either pass it as an argument or set the PIPEDREAM_CLIENT_ID environment variable",
                    });
                }

                const clientSecret =
                    (await core.Supplier.get(this._clientSecret)) ?? process.env?.PIPEDREAM_CLIENT_SECRET;
                if (clientSecret == null) {
                    throw new errors.PipedreamError({
                        message:
                            "clientSecret is required; either pass it as an argument or set the PIPEDREAM_CLIENT_SECRET environment variable",
                    });
                }
                const tokenResponse = await this._authClient.create({
                    clientId: clientId,
                    clientSecret: clientSecret,
                });

                this._accessToken = tokenResponse.accessToken;
                this._expiresAt = this.getExpiresAt(tokenResponse.expiresIn, this.BUFFER_IN_MINUTES);
                return this._accessToken;
            } finally {
                this._refreshPromise = undefined;
            }
        })();
        return this._refreshPromise;
    }

    private getExpiresAt(expiresInSeconds: number, bufferInMinutes: number): Date {
        const now = new Date();
        return new Date(now.getTime() + expiresInSeconds * 1000 - bufferInMinutes * 60 * 1000);
    }
}

export namespace OAuthAuthProvider {
    export interface AuthOptions {
        clientId?: core.Supplier<string> | undefined;
        clientSecret?: core.Supplier<string> | undefined;
    }

    export type Options = BaseClientOptions;
}
